//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSMutableData, NSString, OATask;

__attribute__((visibility("hidden")))
@interface GBActivity : NSObject
{
    OATask *task;
    BOOL isRunning;
    NSDate *date;
    NSString *path;
    NSString *command;
    NSString *status;
    NSString *textOutput;
    NSMutableData *data;
    NSString *dataLength;
}

@property(copy, nonatomic) NSString *dataLength; // @synthesize dataLength;
@property(retain, nonatomic) NSMutableData *data; // @synthesize data;
@property(copy, nonatomic) NSString *textOutput; // @synthesize textOutput;
@property(copy, nonatomic) NSString *status; // @synthesize status;
@property(copy, nonatomic) NSString *command; // @synthesize command;
@property(copy, nonatomic) NSString *path; // @synthesize path;
@property(retain, nonatomic) NSDate *date; // @synthesize date;
@property(nonatomic) BOOL isRunning; // @synthesize isRunning;
@property(nonatomic) OATask *task; // @synthesize task;
- (id)line;
- (void)trimIfNeeded;
- (void)appendData:(id)arg1;
- (id)init;
- (void)dealloc;

@end

