//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "GBAskPassServer-Protocol.h"
#import "NSConnectionDelegate-Protocol.h"

@class NSConnection, NSMutableDictionary, NSMutableSet, NSString;

__attribute__((visibility("hidden")))
@interface GBAskPassServer : NSObject <NSConnectionDelegate, GBAskPassServer>
{
    NSString *name;
    NSMutableSet *clients;
    NSMutableDictionary *resultsByClientId;
    NSConnection *connection;
}

+ (id)remoteServerWithName:(id)arg1;
+ (id)sharedServer;
@property(retain, nonatomic) NSConnection *connection; // @synthesize connection;
@property(retain, nonatomic) NSMutableDictionary *resultsByClientId; // @synthesize resultsByClientId;
@property(retain, nonatomic) NSMutableSet *clients; // @synthesize clients;
@property(copy, nonatomic) NSString *name; // @synthesize name;
- (id)description;
- (id)echo:(id)arg1;
- (id)resultForClient:(id)arg1 prompt:(id)arg2 environment:(id)arg3;
- (void)setResult:(id)arg1 forClientId:(id)arg2;
- (void)removeClient:(id)arg1;
- (void)addClient:(id)arg1;
- (void)invalidate;
- (id)init;
- (void)dealloc;

@end

