//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol GBAskPassServerClient <NSObject>
- (NSString *)resultForClient:(NSString *)arg1 prompt:(NSString *)arg2 environment:(NSDictionary *)arg3;
- (NSString *)askPassClientId;
@end

