//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSString, NSTextField;

__attribute__((visibility("hidden")))
@interface GBAskPassCredentialsController : NSWindowController
{
    CDUnknownBlockType callback;
    NSString *address;
    NSString *username;
    NSString *password;
    NSTextField *addressLabel;
    NSTextField *usernameField;
    NSTextField *passwordField;
}

+ (id)passwordOnlyController;
+ (id)controller;
@property(retain, nonatomic) NSTextField *passwordField; // @synthesize passwordField;
@property(retain, nonatomic) NSTextField *usernameField; // @synthesize usernameField;
@property(retain, nonatomic) NSTextField *addressLabel; // @synthesize addressLabel;
@property(copy, nonatomic) NSString *password; // @synthesize password;
@property(copy, nonatomic) NSString *username; // @synthesize username;
@property(copy, nonatomic) NSString *address; // @synthesize address;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback;
- (void)ok:(id)arg1;
- (void)cancel:(id)arg1;
- (void)windowDidLoad;
- (void)dealloc;

@end

