//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface GBAsyncUpdater : NSObject
{
    BOOL _needsUpdate;
    BOOL _needsUpdateAfterCurrentUpdate;
    BOOL _inProgress;
    int generation;
    id _target;
    SEL _action;
    CDUnknownBlockType currentWaitBlock;
    CDUnknownBlockType nextWaitBlock;
}

+ (id)updaterWithTarget:(id)arg1 action:(SEL)arg2;
@property(copy, nonatomic) CDUnknownBlockType nextWaitBlock; // @synthesize nextWaitBlock;
@property(copy, nonatomic) CDUnknownBlockType currentWaitBlock; // @synthesize currentWaitBlock;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) id target; // @synthesize target=_target;
- (void)cancel;
- (void)endUpdate;
- (void)beginUpdate;
- (void)waitUpdate:(CDUnknownBlockType)arg1;
- (void)setNeedsUpdate;
- (BOOL)isUpdating;
- (BOOL)needsUpdate;
- (void)dealloc;

@end

