//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSString, NSTextField;

__attribute__((visibility("hidden")))
@interface GBAskPassBooleanPromptController : NSWindowController
{
    CDUnknownBlockType callback;
    NSString *address;
    NSString *question;
    NSTextField *addressLabel;
    NSTextField *questionLabel;
}

+ (id)controller;
@property(retain, nonatomic) NSTextField *questionLabel; // @synthesize questionLabel;
@property(retain, nonatomic) NSTextField *addressLabel; // @synthesize addressLabel;
@property(copy, nonatomic) NSString *question; // @synthesize question;
@property(copy, nonatomic) NSString *address; // @synthesize address;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback;
- (void)yes:(id)arg1;
- (void)no:(id)arg1;
- (void)windowDidLoad;
- (void)dealloc;

@end

