//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBTaskWithProgress.h"

#import "GBAskPassServerClient-Protocol.h"

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface GBAuthenticatedTask : GBTaskWithProgress <GBAskPassServerClient>
{
    struct OpaqueSecKeychainItemRef *keychainItem;
    BOOL displayingPrompt;
    BOOL needsStoreCredentialsInKeychain;
    NSString *_remoteAddress;
    BOOL _silent;
    BOOL _authenticationFailed;
    BOOL _authenticationCancelledByUser;
    NSString *_askPassClientId;
    NSString *_username;
    NSString *_password;
    NSNumber *_booleanResponse;
}

@property(retain, nonatomic) NSNumber *booleanResponse; // @synthesize booleanResponse=_booleanResponse;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *askPassClientId; // @synthesize askPassClientId=_askPassClientId;
@property(nonatomic, getter=isAuthenticationCancelledByUser) BOOL authenticationCancelledByUser; // @synthesize authenticationCancelledByUser=_authenticationCancelledByUser;
@property(nonatomic, getter=isAuthenticationFailed) BOOL authenticationFailed; // @synthesize authenticationFailed=_authenticationFailed;
@property(nonatomic, getter=isSilent) BOOL silent; // @synthesize silent=_silent;
@property(copy, nonatomic) NSString *remoteAddress; // @synthesize remoteAddress=_remoteAddress;
- (BOOL)storeCredentialsInKeychain;
- (BOOL)loadCredentialsFromKeychain;
- (void)deleteKeychainItem;
- (id)keychainServiceName;
- (void)presentPasswordPrompt:(id)arg1;
- (void)presentUsernamePrompt:(id)arg1;
- (void)presentBooleanPrompt:(id)arg1;
- (BOOL)isAddressMarkedAsFailed;
- (void)setAddressAsFailed:(BOOL)arg1;
- (id)resultForClient:(id)arg1 prompt:(id)arg2 environment:(id)arg3;
- (void)didFinish;
- (void)willLaunchTask;
- (id)init;
- (void)dealloc;

@end

