//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBWindowControllerWithCallback.h"

#import "NSTextViewDelegate-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

__attribute__((visibility("hidden")))
@interface GBBasePromptController : GBWindowControllerWithCallback <NSWindowDelegate, NSTextViewDelegate>
{
}

- (void)windowDidResignKey:(id)arg1;
- (void)windowDidLoad;
- (void)windowDidBecomeKey:(id)arg1;
- (void)updateWindow;
- (void)onCancel:(id)arg1;
- (void)onOK:(id)arg1;
- (void)dealloc;

@end

