//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "GBChangeDelegate-Protocol.h"
#import "QLPreviewPanelDataSource-Protocol.h"
#import "QLPreviewPanelDelegate-Protocol.h"

@class GBCommit, GBRepositoryController, NSArray, NSArrayController, NSTableView, NSView, QLPreviewPanel;

__attribute__((visibility("hidden")))
@interface GBBaseChangesController : NSViewController <NSTableViewDelegate, NSUserInterfaceValidations, QLPreviewPanelDataSource, QLPreviewPanelDelegate, GBChangeDelegate>
{
    int delaySetChanges;
    GBRepositoryController *repositoryController;
    GBCommit *commit;
    NSTableView *tableView;
    NSArrayController *statusArrayController;
    NSView *headerView;
    NSArray *changes;
    NSArray *changesWithHeaderForBindings;
    QLPreviewPanel *quicklookPanel;
}

@property(retain, nonatomic) QLPreviewPanel *quicklookPanel; // @synthesize quicklookPanel;
@property(retain, nonatomic) NSArray *changesWithHeaderForBindings; // @synthesize changesWithHeaderForBindings;
@property(retain, nonatomic) NSArray *changes; // @synthesize changes;
@property(retain, nonatomic) NSView *headerView; // @synthesize headerView;
@property(retain, nonatomic) NSArrayController *statusArrayController; // @synthesize statusArrayController;
@property(retain, nonatomic) NSTableView *tableView; // @synthesize tableView;
@property(retain, nonatomic) GBCommit *commit; // @synthesize commit;
@property(nonatomic) GBRepositoryController *repositoryController; // @synthesize repositoryController;
- (id)previewPanel:(id)arg1 transitionImageForPreviewItem:(id)arg2 contentRect:(struct CGRect *)arg3;
- (struct CGRect)previewPanel:(id)arg1 sourceFrameOnScreenForPreviewItem:(id)arg2;
- (BOOL)previewPanel:(id)arg1 handleEvent:(id)arg2;
- (id)previewPanel:(id)arg1 previewItemAtIndex:(long long)arg2;
- (long long)numberOfPreviewItemsInPreviewPanel:(id)arg1;
- (void)endPreviewPanelControl:(id)arg1;
- (void)beginPreviewPanelControl:(id)arg1;
- (BOOL)acceptsPreviewPanelControl:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)selectFirstLineIfNeeded:(id)arg1;
- (BOOL)validateSelectRightPane:(id)arg1;
- (void)selectRightPane:(id)arg1;
- (BOOL)validateSelectLeftPane:(id)arg1;
- (void)selectLeftPane:(id)arg1;
- (void)selectPane:(id)arg1;
- (BOOL)validateStageRevealInFinder:(id)arg1;
- (void)stageRevealInFinder:(id)arg1;
- (BOOL)validateStageShowDifference:(id)arg1;
- (void)stageShowDifference:(id)arg1;
- (BOOL)validateShowFileHistory:(id)arg1;
- (void)showFileHistory:(id)arg1;
- (BOOL)tableView:(id)arg1 writeRowsWithIndexes:(id)arg2 toPasteboard:(id)arg3;
- (void)tableViewSelectionDidChange:(id)arg1;
- (id)tableView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;
- (id)tableView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 row:(long long)arg5 mouseLocation:(struct CGPoint)arg6;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (id)tableView:(id)arg1 dataCellForTableColumn:(id)arg2 row:(long long)arg3;
- (void)updateChanges;
- (double)headerHeight;
- (id)headerCell;
- (id)selectedChanges;
- (void)doubleClickChange:(id)arg1;
- (void)unstageChange:(id)arg1;
- (void)stageChange:(id)arg1;
- (void)commitDidUpdateChanges:(id)arg1;
- (void)dealloc;

@end

