//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSCell.h>

__attribute__((visibility("hidden")))
@interface GBCell : NSCell
{
    BOOL isFocused;
}

@property BOOL isFocused; // @synthesize isFocused;

@end

