//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

@class NSView;

__attribute__((visibility("hidden")))
@interface GBCellWithView : NSTextFieldCell
{
    NSView *view;
    double verticalOffset;
    BOOL isViewManagementDisabled;
}

+ (id)cellWithView:(id)arg1;
@property(nonatomic) BOOL isViewManagementDisabled; // @synthesize isViewManagementDisabled;
@property(nonatomic) double verticalOffset; // @synthesize verticalOffset;
@property(nonatomic) NSView *view; // @synthesize view;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

