//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@class GBChange;

@protocol GBChangeDelegate <NSObject>
- (void)doubleClickChange:(GBChange *)arg1;
- (void)unstageChange:(GBChange *)arg1;
- (void)stageChange:(GBChange *)arg1;
@end

