//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBTask.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface GBChangesBaseTask : GBTask
{
    NSArray *changes;
}

@property(retain) NSArray *changes; // @synthesize changes;
- (void)initializeChange:(id)arg1;
- (id)changesFromDiffOutput:(id)arg1;
- (void)didFinish;
- (void)dealloc;

@end

