//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

@class GBChange, NSParagraphStyle;

__attribute__((visibility("hidden")))
@interface GBChangeCell : NSTextFieldCell
{
    NSParagraphStyle *truncatingParagraphStyle;
    BOOL isFocused;
    BOOL isDragging;
}

+ (double)cellHeight;
+ (id)cell;
@property(nonatomic) BOOL isDragging; // @synthesize isDragging;
@property(nonatomic) BOOL isFocused; // @synthesize isFocused;
@property(copy, nonatomic) NSParagraphStyle *truncatingParagraphStyle; // @synthesize truncatingParagraphStyle;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (void)drawPath:(id)arg1 inRect:(struct CGRect)arg2 withAttributes:(id)arg3;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
@property(readonly, nonatomic) GBChange *change; // @dynamic change;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;

@end

