//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSPasteboardWriting-Protocol.h"
#import "QLPreviewItem-Protocol.h"

@class GBRepository, GBSearchQuery, NSImage, NSSet, NSString, NSURL;
@protocol GBChangeDelegate;

__attribute__((visibility("hidden")))
@interface GBChange : NSObject <NSPasteboardWriting, QLPreviewItem>
{
    BOOL relaunchingOpendiff;
    NSURL *srcURL;
    NSURL *dstURL;
    NSString *statusCode;
    NSString *status;
    long long statusScore;
    NSString *srcMode;
    NSString *dstMode;
    NSString *srcRevision;
    NSString *dstRevision;
    NSString *commitId;
    NSImage *cachedSrcIcon;
    NSImage *cachedDstIcon;
    NSURL *quicklookItemURL;
    GBSearchQuery *searchQuery;
    NSSet *highlightedPathSubstrings;
    BOOL containsHighlightedDiffLines;
    BOOL staged;
    id <GBChangeDelegate> delegate;
    BOOL busy;
    GBRepository *repository;
}

+ (id)diffTools;
+ (id)defaultDiffTool;
+ (id)dummy;
@property(nonatomic) GBRepository *repository; // @synthesize repository;
@property(nonatomic) BOOL busy; // @synthesize busy;
@property(nonatomic) id <GBChangeDelegate> delegate; // @synthesize delegate;
@property(nonatomic) BOOL staged; // @synthesize staged;
@property(nonatomic) BOOL containsHighlightedDiffLines; // @synthesize containsHighlightedDiffLines;
@property(copy, nonatomic) NSSet *highlightedPathSubstrings; // @synthesize highlightedPathSubstrings;
@property(retain, nonatomic) GBSearchQuery *searchQuery; // @synthesize searchQuery;
@property(retain, nonatomic) NSURL *quicklookItemURL; // @synthesize quicklookItemURL;
@property(retain, nonatomic) NSImage *cachedDstIcon; // @synthesize cachedDstIcon;
@property(retain, nonatomic) NSImage *cachedSrcIcon; // @synthesize cachedSrcIcon;
@property(copy, nonatomic) NSString *commitId; // @synthesize commitId;
@property(copy, nonatomic) NSString *dstRevision; // @synthesize dstRevision;
@property(copy, nonatomic) NSString *srcRevision; // @synthesize srcRevision;
@property(copy, nonatomic) NSString *dstMode; // @synthesize dstMode;
@property(copy, nonatomic) NSString *srcMode; // @synthesize srcMode;
@property(nonatomic) long long statusScore; // @synthesize statusScore;
@property(copy, nonatomic) NSString *status; // @synthesize status;
@property(copy, nonatomic) NSString *statusCode; // @synthesize statusCode;
@property(retain, nonatomic) NSURL *dstURL; // @synthesize dstURL;
@property(retain, nonatomic) NSURL *srcURL; // @synthesize srcURL;
- (id)temporaryURLForObjectId:(id)arg1 optionalURL:(id)arg2 commitId:(id)arg3;
@property(readonly) NSString *previewItemTitle;
@property(readonly) NSURL *previewItemURL;
- (void)prepareQuicklookItemWithBlock:(CDUnknownBlockType)arg1;
- (id)QLPreviewItem;
- (unsigned long long)writingOptionsForType:(id)arg1 pasteboard:(id)arg2;
- (id)writableTypesForPasteboard:(id)arg1;
- (id)pasteboardPropertyListForType:(id)arg1;
- (id)pasteboardItem;
- (void)extractFileWithTargetURL:(id)arg1;
- (id)nameForExtractedFileWithSuffix;
- (id)uniqueSuffix;
- (id)defaultNameForExtractedFile;
- (BOOL)validateExtractFile;
- (BOOL)validateRevealInFinder;
- (void)revealInFinder;
- (BOOL)validateShowDifference;
- (void)launchDiffWithBlock:(CDUnknownBlockType)arg1;
- (void)doubleClick:(id)arg1;
- (id)cell;
- (Class)cellClass;
- (id)nilIfBusy;
- (id)pathForIgnore;
- (long long)compareByPath:(id)arg1;
- (BOOL)isDirtySubmodule;
- (BOOL)isSubmodule;
- (BOOL)isMovedOrRenamedFile;
- (BOOL)isUntrackedFile;
- (BOOL)isDeletedFile;
- (BOOL)isAddedFile;
- (id)pathStatus;
- (id)statusForStatusCode:(id)arg1;
- (id)submodule;
- (id)dstIcon;
- (id)srcIcon;
- (id)iconForPath:(id)arg1;
- (id)srcIconOrDstIcon;
- (id)icon;
- (id)fileURL;
- (BOOL)isRealChange;
- (id)description;
- (void)setStagedSilently:(BOOL)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly) id previewItemDisplayState;

@end

