//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBAuthenticatedTask.h"

@class NSString, NSURL;

__attribute__((visibility("hidden")))
@interface GBCloneTask : GBAuthenticatedTask
{
    NSString *sourceURLString;
    NSURL *targetURL;
    NSString *status;
    double progress;
}

@property double progress; // @synthesize progress;
@property(copy) NSString *status; // @synthesize status;
@property(retain, nonatomic) NSURL *targetURL; // @synthesize targetURL;
@property(retain, nonatomic) NSString *sourceURLString; // @synthesize sourceURLString;
- (id)arguments;
- (id)currentDirectoryPath;
- (BOOL)ignoreMissingRepository;
- (void)dealloc;

@end

