//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "NSOpenSavePanelDelegate-Protocol.h"
#import "NSTextFieldDelegate-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

@class NSButton, NSString, NSTextField, NSURL;

__attribute__((visibility("hidden")))
@interface GBCloneWindowController : NSWindowController <NSWindowDelegate, NSTextFieldDelegate, NSOpenSavePanelDelegate>
{
    NSTextField *urlField;
    NSButton *nextButton;
    CDUnknownBlockType finishBlock;
    NSString *sourceURLString;
    NSURL *targetDirectoryURL;
    NSURL *targetURL;
}

+ (void)setLastURLString:(id)arg1;
@property(retain) NSURL *targetURL; // @synthesize targetURL;
@property(retain) NSURL *targetDirectoryURL; // @synthesize targetDirectoryURL;
@property(retain) NSString *sourceURLString; // @synthesize sourceURLString;
@property(copy) CDUnknownBlockType finishBlock; // @synthesize finishBlock;
@property(retain) NSButton *nextButton; // @synthesize nextButton;
@property(retain) NSTextField *urlField; // @synthesize urlField;
- (void)update;
- (id)urlStringFromTextField;
- (void)panel:(id)arg1 didChangeToDirectoryURL:(id)arg2;
- (id)panel:(id)arg1 userEnteredFilename:(id)arg2 confirmed:(BOOL)arg3;
- (BOOL)panel:(id)arg1 validateURL:(id)arg2 error:(id *)arg3;
- (void)controlTextDidChange:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowDidLoad;
- (void)ok:(id)arg1;
- (void)cancel:(id)arg1;
- (void)start;
- (void)dealloc;

@end

