//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSArray, NSImageView, NSString;

__attribute__((visibility("hidden")))
@interface GBColorLabelPicker : NSView
{
    NSString *value;
    NSString *highlightedValue;
    id representedObject;
    id target;
    SEL action;
    NSImageView *selectionImageView;
    NSImageView *highlightImageView;
    NSArray *buttons;
}

+ (id)pickerWithTarget:(id)arg1 action:(SEL)arg2 object:(id)arg3;
@property(retain, nonatomic) NSArray *buttons; // @synthesize buttons;
@property(retain, nonatomic) NSImageView *highlightImageView; // @synthesize highlightImageView;
@property(retain, nonatomic) NSImageView *selectionImageView; // @synthesize selectionImageView;
@property(nonatomic) SEL action; // @synthesize action;
@property(nonatomic) id target; // @synthesize target;
@property(retain, nonatomic) id representedObject; // @synthesize representedObject;
@property(retain, nonatomic) NSString *highlightedValue; // @synthesize highlightedValue;
@property(retain, nonatomic) NSString *value; // @synthesize value;
- (void)didUnhighlightValue:(id)arg1;
- (void)didHighlightValue:(id)arg1;
- (void)didClickValue:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGRect)frameForIndex:(int)arg1;
- (id)allValues;
- (void)dealloc;

@end

