//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class GBRepository, GBSearchQuery, NSArray, NSDate, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface GBCommit : NSObject
{
    NSString *commitId;
    NSString *treeId;
    NSString *authorName;
    NSString *authorEmail;
    NSString *committerName;
    NSString *committerEmail;
    NSDate *date;
    NSString *message;
    NSArray *parentIds;
    NSArray *changes;
    NSArray *diffs;
    int rawTimestamp;
    GBSearchQuery *searchQuery;
    BOOL matchesQuery;
    NSDictionary *foundRangesByProperties;
    int syncStatus;
    GBRepository *repository;
    NSString *colorLabel;
}

@property(nonatomic) GBRepository *repository; // @synthesize repository;
@property(nonatomic) int syncStatus; // @synthesize syncStatus;
@property(retain, nonatomic) NSDictionary *foundRangesByProperties; // @synthesize foundRangesByProperties;
@property(nonatomic) BOOL matchesQuery; // @synthesize matchesQuery;
@property(retain, nonatomic) GBSearchQuery *searchQuery; // @synthesize searchQuery;
@property(nonatomic) int rawTimestamp; // @synthesize rawTimestamp;
@property(copy, nonatomic) NSArray *diffs; // @synthesize diffs;
@property(retain, nonatomic) NSArray *changes; // @synthesize changes;
@property(copy, nonatomic) NSArray *parentIds; // @synthesize parentIds;
@property(copy, nonatomic) NSString *message; // @synthesize message;
@property(copy, nonatomic) NSDate *date; // @synthesize date;
@property(copy, nonatomic) NSString *committerEmail; // @synthesize committerEmail;
@property(copy, nonatomic) NSString *committerName; // @synthesize committerName;
@property(copy, nonatomic) NSString *authorEmail; // @synthesize authorEmail;
@property(copy, nonatomic) NSString *authorName; // @synthesize authorName;
@property(copy, nonatomic) NSString *treeId; // @synthesize treeId;
@property(copy, nonatomic) NSString *commitId; // @synthesize commitId;
- (void)loadChangesWithBlock:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) NSString *colorLabel; // @synthesize colorLabel;
- (void)updateSearchAttributes;
- (void)updateSearchAttributesForChanges;
- (id)tags;
- (id)subjectOrCommitIDForMenuItem;
- (id)subjectForReply;
- (id)shortSubject;
- (id)subject;
- (id)tooltipMessage;
- (id)fullDateString;
- (BOOL)isEqual:(id)arg1;
- (id)valueForUndefinedKey:(id)arg1;
- (id)longAuthorLine;
- (BOOL)isMerge;
- (id)asStage;
- (BOOL)isStage;
- (id)description;
- (void)dealloc;

@end

