//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBWindowControllerWithCallback.h"

@class NSButton, NSTextField;

__attribute__((visibility("hidden")))
@interface GBConfirmationController : GBWindowControllerWithCallback
{
    NSTextField *promptTextField;
    NSTextField *descriptionTextField;
    NSButton *okButton;
}

+ (id)controllerWithPrompt:(id)arg1 description:(id)arg2 ok:(id)arg3;
+ (id)controllerWithPrompt:(id)arg1 description:(id)arg2;
@property(retain, nonatomic) NSButton *okButton; // @synthesize okButton;
@property(retain, nonatomic) NSTextField *descriptionTextField; // @synthesize descriptionTextField;
@property(retain, nonatomic) NSTextField *promptTextField; // @synthesize promptTextField;
- (void)onCancel:(id)arg1;
- (void)onOK:(id)arg1;
- (void)dealloc;

@end

