//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

@class GBCommit, GBStage, NSDictionary;

__attribute__((visibility("hidden")))
@interface GBCommitCell : NSTextFieldCell
{
    BOOL isForeground;
    BOOL isFocused;
    NSDictionary *attributes;
    GBStage *stage;
    BOOL cachedStage;
}

+ (id)cell;
+ (double)cellHeight;
@property(nonatomic) BOOL cachedStage; // @synthesize cachedStage;
@property(retain, nonatomic) GBStage *stage; // @synthesize stage;
@property(retain, nonatomic) NSDictionary *attributes; // @synthesize attributes;
@property(nonatomic) BOOL isFocused; // @synthesize isFocused;
@property(nonatomic) BOOL isForeground; // @synthesize isForeground;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawStageContentInFrame:(struct CGRect)arg1;
- (struct CGRect)drawTagBadgesAndReturnRemainingRect:(struct CGRect)arg1;
- (void)drawContentInFrame:(struct CGRect)arg1;
- (void)drawSyncStatusIconInRect:(struct CGRect)arg1;
- (struct CGRect)innerRectForFrame:(struct CGRect)arg1;
- (id)tooltipString;
@property(retain, nonatomic) GBCommit *commit; // @dynamic commit;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCommit:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;
- (void)setupCell;
- (id)attribute:(id)arg1;
- (void)prepareAttributesIfNeeded;
- (id)dateFormatterWithTemplate:(id)arg1;
- (void)dealloc;

@end

