//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBBaseChangesController.h"

@class GBUserpicController, NSBox, NSData, NSImageView, NSTextView;

__attribute__((visibility("hidden")))
@interface GBCommitViewController : GBBaseChangesController <NSSplitViewDelegate, NSOpenSavePanelDelegate>
{
    NSData *headerRTFTemplate;
    NSTextView *headerTextView;
    NSTextView *messageTextView;
    NSBox *horizontalLine;
    NSImageView *authorImage;
    GBUserpicController *userpicController;
}

@property(retain, nonatomic) GBUserpicController *userpicController; // @synthesize userpicController;
@property(retain) NSImageView *authorImage; // @synthesize authorImage;
@property(retain) NSBox *horizontalLine; // @synthesize horizontalLine;
@property(retain) NSTextView *messageTextView; // @synthesize messageTextView;
@property(retain) NSTextView *headerTextView; // @synthesize headerTextView;
@property(retain) NSData *headerRTFTemplate; // @synthesize headerRTFTemplate;
- (void)highlightURLsInAttributedString:(id)arg1;
- (void)panel:(id)arg1 didChangeToDirectoryURL:(id)arg2;
- (id)panel:(id)arg1 userEnteredFilename:(id)arg2 confirmed:(BOOL)arg3;
- (BOOL)panel:(id)arg1 validateURL:(id)arg2 error:(id *)arg3;
- (void)tableViewDidLiveResizeDelayed;
- (void)tableViewDidResize:(id)arg1;
- (void)selectCommitId:(id)arg1;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)doubleClickChange:(id)arg1;
- (BOOL)validateStageExtractFile:(id)arg1;
- (void)stageExtractFile:(id)arg1;
- (void)fixupRareGlitchWithTextView;
- (void)updateHeaderSize;
- (id)mailtoLinkForEmail:(id)arg1 commit:(id)arg2;
- (void)updateTemplate:(id)arg1 withCommit:(id)arg2;
- (void)updateMessageStorage:(id)arg1;
- (void)updateCommitHeader;
- (void)updateViews;
- (void)loadView;
- (void)setChanges:(id)arg1;
- (void)setCommit:(id)arg1;
- (void)dealloc;

@end

