//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSImageView.h>

@class GBColorLabelPicker, NSString;

__attribute__((visibility("hidden")))
@interface GBColorLabelPickerButton : NSImageView
{
    GBColorLabelPicker *picker;
    NSString *value;
    BOOL selected;
}

+ (id)buttonWithValue:(id)arg1 picker:(id)arg2;
@property(nonatomic) BOOL selected; // @synthesize selected;
@property(nonatomic) NSString *value; // @synthesize value;
@property(nonatomic) GBColorLabelPicker *picker; // @synthesize picker;
- (void)viewDidMoveToWindow;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

