//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBChangesBaseTask.h"

@class GBCommit;

__attribute__((visibility("hidden")))
@interface GBCommittedChangesTask : GBChangesBaseTask
{
    GBCommit *commit;
}

@property(retain) GBCommit *commit; // @synthesize commit;
- (void)initializeChange:(id)arg1;
- (id)arguments;
- (void)dealloc;

@end

