//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSString, OAFSEventStream;

__attribute__((visibility("hidden")))
@interface GBFolderMonitor : NSObject
{
    OAFSEventStream *eventStream;
    NSString *path;
    id target;
    SEL action;
    NSDate *folderResumeDate;
    NSDate *dotgitResumeDate;
    long long folderPauseCounter;
    long long dotgitPauseCounter;
    BOOL folderIsUpdated;
    BOOL dotgitIsUpdated;
    BOOL dotgitIsPaused;
}

@property(nonatomic) BOOL dotgitIsPaused; // @synthesize dotgitIsPaused;
@property(nonatomic) BOOL dotgitIsUpdated; // @synthesize dotgitIsUpdated;
@property(nonatomic) BOOL folderIsUpdated; // @synthesize folderIsUpdated;
@property(nonatomic) long long dotgitPauseCounter; // @synthesize dotgitPauseCounter;
@property(nonatomic) long long folderPauseCounter; // @synthesize folderPauseCounter;
@property(retain, nonatomic) NSDate *dotgitResumeDate; // @synthesize dotgitResumeDate;
@property(retain, nonatomic) NSDate *folderResumeDate; // @synthesize folderResumeDate;
@property(nonatomic) SEL action; // @synthesize action;
@property(nonatomic) id target; // @synthesize target;
@property(copy, nonatomic) NSString *path; // @synthesize path;
@property(retain, nonatomic) OAFSEventStream *eventStream; // @synthesize eventStream;
- (void)eventStreamDidUpdate:(id)arg1;
- (id)description;
- (void)resumeFolder;
- (void)pauseFolder;
- (void)resumeDotGit;
- (void)pauseDotGit;
- (void)dealloc;

@end

