//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class GBRepository, OABlockTable;

__attribute__((visibility("hidden")))
@interface GBGitConfig : NSObject
{
    OABlockTable *blockTable;
    BOOL disabledPathQuoting;
    GBRepository *repository;
}

+ (id)configForRepository:(id)arg1;
+ (id)userConfig;
@property(nonatomic) GBRepository *repository; // @synthesize repository;
@property(nonatomic) BOOL disabledPathQuoting; // @synthesize disabledPathQuoting;
@property(retain, nonatomic) OABlockTable *blockTable; // @synthesize blockTable;
- (void)setName:(id)arg1 email:(id)arg2 withBlock:(CDUnknownBlockType)arg3;
- (void)ensureDisabledPathQuoting:(CDUnknownBlockType)arg1;
- (void)setString:(id)arg1 forKey:(id)arg2 withBlock:(CDUnknownBlockType)arg3;
- (void)stringForKey:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (id)userEmail;
- (id)userName;
- (void)removeKey:(id)arg1;
- (void)setString:(id)arg1 forKey:(id)arg2;
- (id)stringForKey:(id)arg1;
- (BOOL)isUserConfig;
- (id)init;
- (void)dealloc;

@end

