//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSColor, NSGradient;

__attribute__((visibility("hidden")))
@interface GBGreyGradientView : NSView
{
    NSGradient *gradient;
    NSColor *lineColor;
}

@property(retain, nonatomic) NSColor *lineColor; // @synthesize lineColor;
@property(retain, nonatomic) NSGradient *gradient; // @synthesize gradient;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;

@end

