//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBTask.h"

@class GBRef, NSArray;

__attribute__((visibility("hidden")))
@interface GBHistoryTask : GBTask
{
    GBRef *branch;
    GBRef *joinedBranch;
    GBRef *substructedBranch;
    int beforeTimestamp;
    BOOL includeDiff;
    unsigned long long limit;
    unsigned long long skip;
    NSArray *commits;
}

@property(retain, nonatomic) NSArray *commits; // @synthesize commits;
@property(nonatomic) unsigned long long skip; // @synthesize skip;
@property(nonatomic) unsigned long long limit; // @synthesize limit;
@property(nonatomic) BOOL includeDiff; // @synthesize includeDiff;
@property(nonatomic) int beforeTimestamp; // @synthesize beforeTimestamp;
@property(retain, nonatomic) GBRef *substructedBranch; // @synthesize substructedBranch;
@property(retain, nonatomic) GBRef *joinedBranch; // @synthesize joinedBranch;
@property(retain, nonatomic) GBRef *branch; // @synthesize branch;
- (id)commitsFromRawFormatData:(id)arg1;
- (void)didFinishInBackground;
- (id)arguments;
- (void)dealloc;

@end

