//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "GBSearchBarControllerDelegate-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"
#import "NSUserInterfaceValidations-Protocol.h"

@class GBCommit, GBCommitCell, GBCommitViewController, GBRepositoryController, GBSearchBarController, GBStageViewController, NSArray, NSArrayController, NSMenu, NSTableView, NSView, OAFastJumpController;

__attribute__((visibility("hidden")))
@interface GBHistoryViewController : NSViewController <NSTableViewDelegate, NSUserInterfaceValidations, GBSearchBarControllerDelegate>
{
    GBRepositoryController *repositoryController;
    GBCommit *commit;
    NSView *detailView;
    NSTableView *tableView;
    NSArrayController *logArrayController;
    NSArray *arrayControllerCommits;
    GBSearchBarController *searchBarController;
    GBStageViewController *stageController;
    GBCommitViewController *commitController;
    OAFastJumpController *jumpController;
    GBCommitCell *commitCell;
    NSMenu *currentMenu;
}

@property(retain, nonatomic) NSMenu *currentMenu; // @synthesize currentMenu;
@property(retain, nonatomic) GBCommitCell *commitCell; // @synthesize commitCell;
@property(retain, nonatomic) OAFastJumpController *jumpController; // @synthesize jumpController;
@property(retain, nonatomic) GBCommitViewController *commitController; // @synthesize commitController;
@property(retain, nonatomic) GBStageViewController *stageController; // @synthesize stageController;
@property(retain, nonatomic) GBSearchBarController *searchBarController; // @synthesize searchBarController;
@property(retain, nonatomic) NSArray *arrayControllerCommits; // @synthesize arrayControllerCommits;
@property(retain, nonatomic) NSArrayController *logArrayController; // @synthesize logArrayController;
@property(retain, nonatomic) NSTableView *tableView; // @synthesize tableView;
@property(retain, nonatomic) NSView *detailView; // @synthesize detailView;
@property(retain, nonatomic) GBCommit *commit; // @synthesize commit;
@property(nonatomic) GBRepositoryController *repositoryController; // @synthesize repositoryController;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (id)tableView:(id)arg1 menuForTableColumn:(id)arg2 row:(long long)arg3;
- (id)tableView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 row:(long long)arg5 mouseLocation:(struct CGPoint)arg6;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (id)tableView:(id)arg1 dataCellForTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)updateStage;
- (BOOL)validateSelectRightPane:(id)arg1;
- (BOOL)validateSelectLeftPane:(id)arg1;
- (void)selectRightPane:(id)arg1;
- (void)selectLeftPane:(id)arg1;
- (void)selectPreviousPane:(id)arg1;
- (void)selectPane:(id)arg1;
- (id)menuForCommit:(id)arg1;
- (void)colorPickerDidChange:(id)arg1;
- (id)menuForStage:(id)arg1;
- (void)prepareChangesControllersIfNeeded;
- (void)loadView;
- (void)repositoryControllerSearchDidStopRunning:(id)arg1;
- (void)repositoryControllerSearchDidStartRunning:(id)arg1;
- (void)repositoryControllerSearchDidTab:(id)arg1;
- (void)repositoryControllerSearchDidEnd:(id)arg1;
- (void)repositoryControllerDidUpdateStage:(id)arg1;
- (void)repositoryControllerDidSelectCommit:(id)arg1;
- (void)repositoryControllerDidUpdateRefs:(id)arg1;
- (void)repositoryControllerDidUpdateCommits:(id)arg1;
@property(retain, nonatomic) NSArray *visibleCommits; // @dynamic visibleCommits;
- (void)dealloc;

@end

