//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSScroller.h>

__attribute__((visibility("hidden")))
@interface GBLightScroller : NSScroller
{
    struct CGRect lastKnobRect;
    double lastKnobAlpha;
    BOOL shouldFadeKnob;
    BOOL mouseIsOverScroller;
}

+ (BOOL)isCompatibleWithOverlayScrollers;
+ (double)width;
+ (BOOL)isModernScroller;
@property(nonatomic) BOOL mouseIsOverScroller; // @synthesize mouseIsOverScroller;
@property(nonatomic) BOOL shouldFadeKnob; // @synthesize shouldFadeKnob;
@property(nonatomic) double lastKnobAlpha; // @synthesize lastKnobAlpha;
@property(nonatomic) struct CGRect lastKnobRect; // @synthesize lastKnobRect;
- (void)drawKnob;
- (void)setNeedsFadeKnob;
- (void)setNeedsDisplayKnob;
- (void)drawKnobSlotInRect:(struct CGRect)arg1 highlight:(BOOL)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)isOpaque;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

