//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBTask.h"

@class NSArray, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface GBLocalRefsTask : GBTask
{
    NSArray *branches;
    NSArray *tags;
    NSMutableDictionary *remoteBranchesByRemoteAlias;
}

@property(retain, nonatomic) NSMutableDictionary *remoteBranchesByRemoteAlias; // @synthesize remoteBranchesByRemoteAlias;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags;
@property(retain, nonatomic) NSArray *branches; // @synthesize branches;
- (void)didFinish;
- (id)arguments;
- (void)dealloc;

@end

