//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBTask.h"

@class GBRef, NSString;

__attribute__((visibility("hidden")))
@interface GBLocalRemoteAssociationTask : GBTask
{
    GBRef *remoteBranch;
    NSString *localBranchName;
    NSString *remoteAlias;
    NSString *remoteBranchName;
}

@property(retain, nonatomic) NSString *remoteBranchName; // @synthesize remoteBranchName;
@property(retain, nonatomic) NSString *remoteAlias; // @synthesize remoteAlias;
@property(retain, nonatomic) NSString *localBranchName; // @synthesize localBranchName;
@property(retain, nonatomic) GBRef *remoteBranch; // @synthesize remoteBranch;
- (void)didFinish;
- (id)arguments;
- (void)dealloc;

@end

