//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class GBPlaceholderViewController, GBRootController, GBSidebarController, GBToolbarController, GBWelcomeController, NSSplitView, NSViewController, NSWindow, OABlockQueue, OAFastJumpController;
@protocol GBMainWindowItem;

__attribute__((visibility("hidden")))
@interface GBMainWindowController : NSWindowController <NSSplitViewDelegate>
{
    GBRootController *rootController;
    GBToolbarController *defaultToolbarController;
    GBPlaceholderViewController *defaultDetailViewController;
    GBToolbarController *toolbarController;
    NSViewController *detailViewController;
    id <GBMainWindowItem> selectedWindowItem;
    GBSidebarController *sidebarController;
    GBWelcomeController *welcomeController;
    NSSplitView *splitView;
    OAFastJumpController *jumpController;
    OABlockQueue *sheetQueue;
    NSWindow *currentSheet;
}

+ (id)instance;
@property(retain, nonatomic) NSWindow *currentSheet; // @synthesize currentSheet;
@property(retain, nonatomic) OABlockQueue *sheetQueue; // @synthesize sheetQueue;
@property(retain, nonatomic) OAFastJumpController *jumpController; // @synthesize jumpController;
@property(retain, nonatomic) NSSplitView *splitView; // @synthesize splitView;
@property(retain, nonatomic) GBWelcomeController *welcomeController; // @synthesize welcomeController;
@property(retain, nonatomic) GBSidebarController *sidebarController; // @synthesize sidebarController;
@property(retain, nonatomic) id <GBMainWindowItem> selectedWindowItem; // @synthesize selectedWindowItem;
@property(retain, nonatomic) NSViewController *detailViewController; // @synthesize detailViewController;
@property(retain, nonatomic) GBToolbarController *toolbarController; // @synthesize toolbarController;
@property(retain, nonatomic) GBPlaceholderViewController *defaultDetailViewController; // @synthesize defaultDetailViewController;
@property(retain, nonatomic) GBToolbarController *defaultToolbarController; // @synthesize defaultToolbarController;
@property(retain, nonatomic) GBRootController *rootController; // @synthesize rootController;
- (void)updateToolbarAlignment;
- (id)detailView;
- (id)sidebarView;
- (void)splitViewDidResizeSubviews:(id)arg1;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (void)splitView:(id)arg1 resizeSubviewsWithOldSize:(struct CGSize)arg2;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (id)windowWillReturnUndoManager:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidLoad;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)alertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(CDUnknownBlockType)arg3;
- (void)criticalConfirmationWithMessage:(id)arg1 description:(id)arg2 ok:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)sheetQueueEndBlock;
- (void)sheetQueueAddBlock:(CDUnknownBlockType)arg1;
- (void)dismissSheet;
- (void)dismissSheet:(id)arg1;
- (void)presentSheet:(id)arg1 silent:(BOOL)arg2;
- (void)presentSheet:(id)arg1;
- (void)selectNextPane:(id)arg1;
- (void)selectPreviousPane:(id)arg1;
- (void)showWelcomeWindow:(id)arg1;
- (void)editGlobalGitConfig:(id)arg1;
- (void)rootControllerDidChangeContents:(id)arg1;
- (void)rootControllerDidChangeSelection:(id)arg1;
- (id)initWithWindow:(id)arg1;
- (void)dealloc;

@end

