//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GBToolbarController, NSString, NSURL, NSUndoManager, NSViewController;

@protocol GBMainWindowItem <NSObject>

@optional
- (NSUndoManager *)undoManager;
- (void)didSelectWindowItem;
- (void)willDeselectWindowItem;
- (NSViewController *)viewController;
- (GBToolbarController *)toolbarController;
- (NSURL *)windowRepresentedURL;
- (NSString *)windowTitle;
@end

