//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBWindowControllerWithCallback.h"

@class GBRepository, GBTaskWithProgress, NSProgressIndicator, NSTextField;

__attribute__((visibility("hidden")))
@interface GBOptimizeRepositoryController : GBWindowControllerWithCallback
{
    BOOL started;
    NSProgressIndicator *progressIndicator;
    NSTextField *pathLabel;
    GBRepository *_repository;
    GBTaskWithProgress *_task;
}

+ (void)resetTimeout;
+ (void)scheduleCheck;
+ (void)stopMonitoring;
+ (void)startMonitoring;
+ (BOOL)randomShouldOptimize;
+ (id)controllerWithRepository:(id)arg1;
@property(retain, nonatomic) GBTaskWithProgress *task; // @synthesize task=_task;
@property(retain, nonatomic) GBRepository *repository; // @synthesize repository=_repository;
@property(retain, nonatomic) NSTextField *pathLabel; // @synthesize pathLabel;
@property(retain, nonatomic) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator;
- (void)windowDidLoad;
- (void)start;
- (void)dealloc;

@end

