//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "MASPreferencesViewController-Protocol.h"

@class NSImage, NSString, NSTextField, NSTextView;

__attribute__((visibility("hidden")))
@interface GBPreferencesIgnoreViewController : NSViewController <MASPreferencesViewController>
{
    NSString *labelString;
    NSTextView *textView;
    NSTextField *label;
}

+ (id)controller;
@property NSTextField *label; // @synthesize label;
@property NSTextView *textView; // @synthesize textView;
@property(copy, nonatomic) NSString *labelString; // @synthesize labelString;
- (void)viewWillAppear;
@property(readonly, nonatomic) NSString *toolbarItemLabel;
@property(readonly, nonatomic) NSImage *toolbarItemImage;
@property(readonly, nonatomic) NSString *identifier;
- (void)loadView;
- (void)textDidChange:(id)arg1;
- (void)loadData;
- (id)fileURL;
- (void)dealloc;

@end

