//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBWindowControllerWithCallback.h"

#import "NSWindowDelegate-Protocol.h"

@class NSString, NSTextField;

__attribute__((visibility("hidden")))
@interface GBPromptController : GBWindowControllerWithCallback <NSWindowDelegate>
{
    BOOL didInitField;
    NSTextField *textField;
    NSString *title;
    NSString *promptText;
    NSString *buttonText;
    NSString *value;
    BOOL requireNonNilValue;
    BOOL requireNonEmptyString;
    BOOL requireSingleLine;
    BOOL requireStripWhitespace;
}

+ (id)controller;
@property BOOL requireStripWhitespace; // @synthesize requireStripWhitespace;
@property BOOL requireSingleLine; // @synthesize requireSingleLine;
@property BOOL requireNonEmptyString; // @synthesize requireNonEmptyString;
@property BOOL requireNonNilValue; // @synthesize requireNonNilValue;
@property(copy) NSString *value; // @synthesize value;
@property(copy) NSString *buttonText; // @synthesize buttonText;
@property(copy) NSString *promptText; // @synthesize promptText;
@property(copy) NSString *title; // @synthesize title;
@property(retain) NSTextField *textField; // @synthesize textField;
- (void)windowDidBecomeKey:(id)arg1;
- (void)onCancel:(id)arg1;
- (void)onOK:(id)arg1;
- (void)dealloc;
- (id)initWithWindow:(id)arg1;

@end

