//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "MASPreferencesViewController-Protocol.h"

@class NSImage, NSString;

__attribute__((visibility("hidden")))
@interface GBPreferencesGithubViewController : NSViewController <MASPreferencesViewController>
{
}

+ (id)controller;
@property(readonly, nonatomic) NSString *toolbarItemLabel;
@property(readonly, nonatomic) NSImage *toolbarItemImage;
@property(readonly, nonatomic) NSString *identifier;
- (void)checkboxDidChange:(id)arg1;

@end

