//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "MASPreferencesViewController-Protocol.h"

@class NSImage, NSString;

__attribute__((visibility("hidden")))
@interface GBPreferencesDiffViewController : NSViewController <MASPreferencesViewController>
{
    BOOL loadingDiffToolsStatus;
    BOOL isFileMergeAvailable;
    BOOL isKaleidoscopeAvailable;
    BOOL isChangesAvailable;
    BOOL isTextWranglerAvailable;
    BOOL isBBEditAvailable;
    BOOL isAraxisAvailable;
    BOOL isDiffMergeAvailable;
}

+ (id)controller;
@property BOOL isDiffMergeAvailable; // @synthesize isDiffMergeAvailable;
@property BOOL isAraxisAvailable; // @synthesize isAraxisAvailable;
@property BOOL isBBEditAvailable; // @synthesize isBBEditAvailable;
@property BOOL isTextWranglerAvailable; // @synthesize isTextWranglerAvailable;
@property BOOL isChangesAvailable; // @synthesize isChangesAvailable;
@property BOOL isKaleidoscopeAvailable; // @synthesize isKaleidoscopeAvailable;
@property BOOL isFileMergeAvailable; // @synthesize isFileMergeAvailable;
- (id)initialKeyView;
- (void)viewWillAppear;
@property(readonly, nonatomic) NSString *toolbarItemLabel;
@property(readonly, nonatomic) NSImage *toolbarItemImage;
@property(readonly, nonatomic) NSString *identifier;
- (void)windowDidBecomeKey:(id)arg1;
- (void)checkboxDidChange:(id)arg1;
- (void)loadDiffToolsStatus;
- (id)diffTools;
- (void)dealloc;

@end

