//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBAuthenticatedTask.h"

@class GBRemote, NSArray;

__attribute__((visibility("hidden")))
@interface GBRemoteRefsTask : GBAuthenticatedTask
{
    NSArray *branches;
    NSArray *tags;
    GBRemote *remote;
}

@property(retain, nonatomic) GBRemote *remote; // @synthesize remote;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags;
@property(retain, nonatomic) NSArray *branches; // @synthesize branches;
- (void)didFinish;
- (id)arguments;
- (void)dealloc;

@end

