//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "NSSplitViewDelegate-Protocol.h"

@class GBHistoryViewController, GBRepositoryController, NSSplitView;

__attribute__((visibility("hidden")))
@interface GBRepositoryViewController : NSViewController <NSSplitViewDelegate>
{
    GBRepositoryController *repositoryController;
    GBHistoryViewController *historyController;
    NSSplitView *splitView;
}

@property(retain, nonatomic) NSSplitView *splitView; // @synthesize splitView;
@property(retain, nonatomic) GBHistoryViewController *historyController; // @synthesize historyController;
@property(nonatomic) GBRepositoryController *repositoryController; // @synthesize repositoryController;
- (id)detailView;
- (id)historyView;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (void)swipeWithEvent:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)selectPane:(id)arg1;
- (id)firstKeyView;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

@end

