//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBTask.h"

__attribute__((visibility("hidden")))
@interface GBRefreshIndexTask : GBTask
{
}

- (BOOL)ignoreFailure;
- (id)arguments;

@end

