//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class GBRepository, GBRepositorySettingsController, NSString;

__attribute__((visibility("hidden")))
@interface GBRepositorySettingsViewController : NSViewController
{
    GBRepositorySettingsController *settingsController;
    GBRepository *repository;
    NSString *title;
    BOOL dirty;
}

@property(nonatomic, getter=isDirty) BOOL dirty; // @synthesize dirty;
@property(copy, nonatomic) NSString *title; // @synthesize title;
@property(retain, nonatomic) GBRepository *repository; // @synthesize repository;
@property(nonatomic) GBRepositorySettingsController *settingsController; // @synthesize settingsController;
- (void)criticalConfirmationWithMessage:(id)arg1 description:(id)arg2 ok:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)userInfo;
- (void)popDisabled;
- (void)pushDisabled;
- (BOOL)isDisabled;
- (void)save;
- (void)cancel;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (id)initWithRepository:(id)arg1;
- (void)dealloc;

@end

