//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBTask.h"

@class NSArray, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface GBRemotesTask : GBTask
{
    NSArray *remotes;
    NSMutableDictionary *remotesByAlias;
}

@property(retain, nonatomic) NSMutableDictionary *remotesByAlias; // @synthesize remotesByAlias;
@property(retain, nonatomic) NSArray *remotes; // @synthesize remotes;
- (void)didFinish;
- (id)remoteForAlias:(id)arg1;
- (id)arguments;
- (void)dealloc;

@end

