//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSResponder.h>

#import "GBMainWindowItem-Protocol.h"
#import "GBSidebarItemObject-Protocol.h"

@class GBRepositoriesController, GBSidebarItem, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface GBRepositoriesGroup : NSResponder <GBMainWindowItem, GBSidebarItemObject>
{
    GBSidebarItem *sidebarItem;
    NSString *name;
    NSMutableArray *items;
    GBRepositoriesController *repositoriesController;
    BOOL isExpanded;
}

+ (id)untitledGroup;
@property(nonatomic) BOOL isExpanded; // @synthesize isExpanded;
@property(nonatomic) GBRepositoriesController *repositoriesController; // @synthesize repositoriesController;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items;
@property(copy, nonatomic) NSString *name; // @synthesize name;
@property(retain, nonatomic) GBSidebarItem *sidebarItem; // @synthesize sidebarItem;
- (void)sidebarItemLoadContentsFromPropertyList:(id)arg1;
- (id)sidebarItemContentsPropertyList;
- (id)sidebarItemMenu;
- (BOOL)sidebarItemMoveObjects:(id)arg1 toIndex:(unsigned long long)arg2;
- (BOOL)sidebarItemOpenURLs:(id)arg1 atIndex:(unsigned long long)arg2;
- (unsigned long long)sidebarItemDragOperationForItems:(id)arg1 outlineView:(id)arg2;
- (unsigned long long)sidebarItemDragOperationForURLs:(id)arg1 outlineView:(id)arg2;
- (void)sidebarItemSetStringValue:(id)arg1;
- (id)sidebarItemTooltip;
- (id)sidebarItemTitle;
- (id)sidebarItemChildAtIndex:(long long)arg1;
- (long long)sidebarItemNumberOfChildren;
- (id)windowTitle;
- (BOOL)validateActionForMultipleSelection:(SEL)arg1;
- (void)rename:(id)arg1;
- (id)repositoryControllerWithURL:(id)arg1;
- (void)removeObject:(id)arg1;
- (void)insertObject:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)untitledGroupName;
- (id)init;
- (void)dealloc;

@end

