//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBRepositoriesGroup.h"

#import "NSOpenSavePanelDelegate-Protocol.h"

@class GBCloneWindowController, GBRepositoryToolbarController, GBRepositoryViewController, GBRootController, OAFSEventStream;

__attribute__((visibility("hidden")))
@interface GBRepositoriesController : GBRepositoriesGroup <NSOpenSavePanelDelegate>
{
    GBRootController *rootController;
    GBRepositoryViewController *repositoryViewController;
    GBRepositoryToolbarController *repositoryToolbarController;
    GBCloneWindowController *cloneWindowController;
    OAFSEventStream *fsEventStream;
}

@property(retain, nonatomic) OAFSEventStream *fsEventStream; // @synthesize fsEventStream;
@property(retain, nonatomic) GBCloneWindowController *cloneWindowController; // @synthesize cloneWindowController;
@property(retain, nonatomic) GBRepositoryToolbarController *repositoryToolbarController; // @synthesize repositoryToolbarController;
@property(retain, nonatomic) GBRepositoryViewController *repositoryViewController; // @synthesize repositoryViewController;
@property(nonatomic) GBRootController *rootController; // @synthesize rootController;
- (BOOL)validateAdditionalRepositories:(unsigned long long)arg1;
- (void)repositoryControllerDidStop:(id)arg1;
- (void)repositoryControllerDidUpdateSubmodules:(id)arg1;
- (void)repositoryController:(id)arg1 didMoveToURL:(id)arg2;
- (id)groupAndIndex:(unsigned long long *)arg1 forObject:(id)arg2;
- (id)contextGroupAndIndex:(unsigned long long *)arg1;
- (void)startRepositoryController:(id)arg1;
- (void)configureRepositoryController:(id)arg1;
- (id)sidebarItemTooltip;
- (void)removeObjects:(id)arg1;
- (BOOL)moveObjects:(id)arg1 toGroup:(id)arg2 atIndex:(unsigned long long)arg3;
- (BOOL)openURLs:(id)arg1 inGroup:(id)arg2 atIndex:(unsigned long long)arg3;
- (BOOL)openURLs:(id)arg1;
- (void)cloningRepositoryControllerDidFinish:(id)arg1;
- (void)cloningRepositoryControllerDidCancel:(id)arg1;
- (void)cloningRepositoryControllerDidFail:(id)arg1;
- (void)cloneRepository:(id)arg1;
- (void)cloneRepositoryAtURLString:(id)arg1;
- (void)addGroup:(id)arg1;
- (void)someNewMethod;
- (void)remove:(id)arg1;
- (BOOL)panel:(id)arg1 validateURL:(id)arg2 error:(id *)arg3;
- (void)openDocument:(id)arg1;
- (void)contentsDidChange;
- (id)repositoriesController;
- (id)init;
- (void)dealloc;
- (void)sidebarItemLoadContentsFromPropertyList:(id)arg1;
- (void)loadGroupContents:(id)arg1 fromPropertyList:(id)arg2;
- (id)sidebarItemContentsPropertyList;
- (id)propertyListForRepositoryController:(id)arg1;
- (id)propertyListForGroup:(id)arg1;
- (id)propertyListForGroupContents:(id)arg1;

@end

