//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBWindowControllerWithCallback.h"

#import "NSTabViewDelegate-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

@class GBRepository, NSArray, NSButton, NSMutableDictionary, NSString, NSTabView;

__attribute__((visibility("hidden")))
@interface GBRepositorySettingsController : GBWindowControllerWithCallback <NSTabViewDelegate, NSWindowDelegate>
{
    GBRepository *repository;
    NSMutableDictionary *userInfo;
    NSString *selectedTab;
    NSButton *cancelButton;
    NSButton *saveButton;
    NSTabView *tabView;
    NSArray *viewControllers;
    BOOL dirty;
    BOOL tabsPrepared;
    BOOL disabled;
}

+ (id)controllerWithTab:(id)arg1 repository:(id)arg2;
@property(nonatomic, getter=isDisabled) BOOL disabled; // @synthesize disabled;
@property(nonatomic, getter=areTabsPrepared) BOOL tabsPrepared; // @synthesize tabsPrepared;
@property(nonatomic, getter=isDirty) BOOL dirty; // @synthesize dirty;
@property(retain, nonatomic) NSArray *viewControllers; // @synthesize viewControllers;
@property(retain, nonatomic) NSTabView *tabView; // @synthesize tabView;
@property(retain, nonatomic) NSButton *saveButton; // @synthesize saveButton;
@property(retain, nonatomic) NSButton *cancelButton; // @synthesize cancelButton;
@property(copy, nonatomic) NSString *selectedTab; // @synthesize selectedTab;
@property(retain, nonatomic) NSMutableDictionary *userInfo; // @synthesize userInfo;
@property(retain, nonatomic) GBRepository *repository; // @synthesize repository;
- (void)selectTabViewItemAtIndex:(long long)arg1;
- (void)syncSelectedTab;
- (void)alertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(CDUnknownBlockType)arg3;
- (void)criticalConfirmationWithMessage:(id)arg1 description:(id)arg2 ok:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;
- (void)windowDidLoad;
- (void)viewControllerDidChangeDirtyStatus:(id)arg1;
- (void)popDisabled;
- (void)pushDisabled;
- (void)didUpdateDisabledStatus;
- (void)save:(id)arg1;
- (void)cancel:(id)arg1;
- (void)performCompletionHandler:(BOOL)arg1;
- (void)presentSheetInMainWindow;
- (id)initWithWindow:(id)arg1;
- (void)dealloc;

@end

