//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBRepositorySettingsViewController.h"

@class NSArray, NSTextField, NSTextView, NSView;

__attribute__((visibility("hidden")))
@interface GBRepositorySummaryController : GBRepositorySettingsViewController
{
    NSArray *remotes;
    NSArray *labels;
    NSArray *fields;
    NSTextField *pathLabel;
    NSTextField *originLabel;
    NSTextField *remoteLabel1;
    NSTextField *remoteField1;
    NSTextField *remoteLabel2;
    NSTextField *remoteField2;
    NSTextField *remoteLabel3;
    NSTextField *remoteField3;
    NSView *remainingView;
    NSTextView *gitignoreTextView;
}

@property NSTextView *gitignoreTextView; // @synthesize gitignoreTextView;
@property NSView *remainingView; // @synthesize remainingView;
@property NSTextField *remoteField3; // @synthesize remoteField3;
@property NSTextField *remoteLabel3; // @synthesize remoteLabel3;
@property NSTextField *remoteField2; // @synthesize remoteField2;
@property NSTextField *remoteLabel2; // @synthesize remoteLabel2;
@property NSTextField *remoteField1; // @synthesize remoteField1;
@property NSTextField *remoteLabel1; // @synthesize remoteLabel1;
@property(retain, nonatomic) NSTextField *originLabel; // @synthesize originLabel;
@property(retain, nonatomic) NSTextField *pathLabel; // @synthesize pathLabel;
@property(retain, nonatomic) NSArray *fields; // @synthesize fields;
@property(retain, nonatomic) NSArray *labels; // @synthesize labels;
@property(retain, nonatomic) NSArray *remotes; // @synthesize remotes;
- (void)didUpdateText:(id)arg1;
- (void)openInFinder:(id)arg1;
- (id)repoURLString;
- (id)repoPath;
- (id)repoTitle;
- (id)parentFolder;
- (void)iterateRemoteLines:(CDUnknownBlockType)arg1;
- (void)save;
- (void)viewDidLoad;
- (id)title;
- (id)initWithRepository:(id)arg1;
- (void)dealloc;

@end

