//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class GBRepositoryCloningController, NSButton, NSProgressIndicator, NSTextField;

__attribute__((visibility("hidden")))
@interface GBRepositoryCloningViewController : NSViewController
{
    NSTextField *messageLabel;
    NSTextField *errorLabel;
    NSButton *cancelButton;
    NSProgressIndicator *progressIndicator;
    GBRepositoryCloningController *repositoryController;
}

@property(nonatomic) GBRepositoryCloningController *repositoryController; // @synthesize repositoryController;
@property(retain, nonatomic) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator;
@property(retain, nonatomic) NSButton *cancelButton; // @synthesize cancelButton;
@property(retain, nonatomic) NSTextField *errorLabel; // @synthesize errorLabel;
@property(retain, nonatomic) NSTextField *messageLabel; // @synthesize messageLabel;
- (void)cloningRepositoryControllerDidFinish:(id)arg1;
- (void)cloningRepositoryControllerDidCancel:(id)arg1;
- (void)cloningRepositoryControllerDidFail:(id)arg1;
- (void)cloningRepositoryControllerProgress:(id)arg1;
- (void)cloningRepositoryControllerDidStart:(id)arg1;
- (void)update;
- (void)cancel:(id)arg1;
- (void)loadView;
- (void)dealloc;

@end

