//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBRepositorySettingsViewController.h"

@class NSString, NSTextView;

__attribute__((visibility("hidden")))
@interface GBRepositoryConfigController : GBRepositorySettingsViewController
{
    NSTextView *textView;
    NSString *contents;
}

@property(copy, nonatomic) NSString *contents; // @synthesize contents;
@property NSTextView *textView; // @synthesize textView;
- (void)save;
- (void)viewDidLoad;
- (id)title;
- (id)initWithRepository:(id)arg1;
- (void)dealloc;

@end

