//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class GBRepository, NSArray, NSString;

__attribute__((visibility("hidden")))
@interface GBRemote : NSObject
{
    NSString *alias;
    NSString *URLString;
    NSString *fetchRefspec;
    NSArray *branches;
    NSArray *transientBranches;
    GBRepository *repository;
    BOOL isUpdatingRemoteBranches;
    BOOL needsFetch;
}

@property(nonatomic) BOOL needsFetch; // @synthesize needsFetch;
@property(nonatomic) BOOL isUpdatingRemoteBranches; // @synthesize isUpdatingRemoteBranches;
@property(nonatomic) GBRepository *repository; // @synthesize repository;
@property(retain, nonatomic) NSArray *transientBranches; // @synthesize transientBranches;
@property(retain, nonatomic) NSArray *branches; // @synthesize branches;
@property(copy, nonatomic) NSString *fetchRefspec; // @synthesize fetchRefspec;
@property(copy, nonatomic) NSString *URLString; // @synthesize URLString;
@property(copy, nonatomic) NSString *alias; // @synthesize alias;
- (BOOL)doesNeedFetchNewBranches:(id)arg1 andTags:(id)arg2;
- (void)updateBranchesSilently:(BOOL)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)addNewBranch:(id)arg1;
- (BOOL)isTransientBranch:(id)arg1;
- (id)defaultFetchRefspec;
- (BOOL)copyInterestingDataFromRemoteIfApplicable:(id)arg1;
- (void)updateBranches;
- (void)updateNewBranches;
- (id)pushedAndNewBranches;
- (id)defaultBranch;
- (id)description;
- (void)dealloc;

@end

