//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface GBRef : NSObject
{
    NSString *name;
    NSString *commitId;
    NSString *remoteAlias;
    GBRef *configuredRemoteBranch;
    BOOL isTag;
}

+ (id)refWithCommitId:(id)arg1;
@property(nonatomic) BOOL isTag; // @synthesize isTag;
@property(retain, nonatomic) GBRef *configuredRemoteBranch; // @synthesize configuredRemoteBranch;
@property(copy, nonatomic) NSString *remoteAlias; // @synthesize remoteAlias;
@property(copy, nonatomic) NSString *commitId; // @synthesize commitId;
@property(copy, nonatomic) NSString *name; // @synthesize name;
- (id)description;
- (id)commitish;
- (id)displayName;
- (BOOL)isRemoteBranch;
- (BOOL)isLocalBranch;
- (void)setNameWithRemoteAlias:(id)arg1;
- (id)nameWithRemoteAlias;
- (BOOL)isEqualToRef:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;

@end

