//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBToolbarController.h"

#import "NSMenuDelegate-Protocol.h"
#import "NSTextFieldDelegate-Protocol.h"

@class GBRepositoryController, NSButton, NSMutableArray, NSPopUpButton, NSSearchField, NSSegmentedControl;

__attribute__((visibility("hidden")))
@interface GBRepositoryToolbarController : GBToolbarController <NSTextFieldDelegate, NSMenuDelegate>
{
    BOOL needsUpdateAfterClosingMenu;
    GBRepositoryController *repositoryController;
    NSMutableArray *_openedMenus;
}

@property(retain, nonatomic) NSMutableArray *openedMenus; // @synthesize openedMenus=_openedMenus;
@property(nonatomic) GBRepositoryController *repositoryController; // @synthesize repositoryController;
- (BOOL)validateCheckoutTagMenu:(id)arg1;
- (BOOL)validateCheckoutRemoteBranchMenu:(id)arg1;
- (BOOL)validateCheckoutBranchMenu:(id)arg1;
- (void)checkoutTagMenu:(id)arg1;
- (void)checkoutRemoteBranchMenu:(id)arg1;
- (void)checkoutBranchMenu:(id)arg1;
- (void)quickCheckout:(id)arg1;
- (void)createNewRemoteBranch:(id)arg1;
- (void)selectRemoteBranch:(id)arg1;
- (void)checkoutCommit:(id)arg1;
- (BOOL)validateNewBranch:(id)arg1;
- (void)newBranch:(id)arg1;
- (void)checkoutRemoteBranch:(id)arg1;
- (void)checkoutBranch:(id)arg1;
- (void)pullOrPush:(id)arg1;
- (BOOL)isMenuOpened:(id)arg1;
- (BOOL)isMenuOpened;
- (void)menuDidClose:(id)arg1;
- (void)menuWillOpen:(id)arg1;
- (void)updateRemoteBranchMenus;
- (void)updateCurrentBranchMenus;
- (void)updateBranchMenus;
- (void)updateSyncButtons;
- (void)updateDisabledState;
- (void)update;
- (double)sidebarPadding;
- (void)flagsChanged:(id)arg1;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)searchFieldDidChange:(id)arg1;
- (void)repositoryControllerSearchDidEnd:(id)arg1;
- (void)repositoryControllerSearchDidStartRunning:(id)arg1;
- (void)repositoryControllerSearchDidStart:(id)arg1;
- (void)repositoryControllerDidUpdateRefs:(id)arg1;
- (void)repositoryControllerDidCommit:(id)arg1;
- (void)repositoryControllerDidChangeRemoteBranch:(id)arg1;
- (void)repositoryControllerDidCheckoutBranch:(id)arg1;
- (void)repositoryControllerDidChangeSpinningStatus:(id)arg1;
- (void)repositoryControllerDidChangeDisabledStatus:(id)arg1;
@property(readonly, nonatomic) NSSearchField *searchField; // @dynamic searchField;
@property(readonly, nonatomic) NSPopUpButton *otherBranchPopUpButton; // @dynamic otherBranchPopUpButton;
@property(readonly, nonatomic) NSButton *pullButton; // @dynamic pullButton;
@property(readonly, nonatomic) NSSegmentedControl *pullPushControl; // @dynamic pullPushControl;
@property(readonly, nonatomic) NSButton *settingsButton;
@property(readonly, nonatomic) NSPopUpButton *currentBranchPopUpButton; // @dynamic currentBranchPopUpButton;
- (BOOL)wantsSettingsButton;
- (id)init;
- (void)dealloc;

@end

