//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSResponder.h>

#import "GBSidebarItemObject-Protocol.h"

@class GBRepositoriesController, GBSidebarItem, NSArray;
@protocol GBSidebarItemObject, GBMainWindowItem;

__attribute__((visibility("hidden")))
@interface GBRootController : NSResponder <GBSidebarItemObject>
{
    GBSidebarItem *sidebarItem;
    GBRepositoriesController *repositoriesController;
    NSArray *nextRespondingSidebarObjects;
    NSArray *_selectedObjects;
    NSResponder<GBSidebarItemObject,GBMainWindowItem> *_selectedObject;
    NSResponder<GBSidebarItemObject,GBMainWindowItem> *_clickedObject;
}

@property(retain, nonatomic) NSResponder<GBSidebarItemObject,GBMainWindowItem> *clickedObject; // @synthesize clickedObject=_clickedObject;
@property(retain, nonatomic) NSResponder<GBSidebarItemObject,GBMainWindowItem> *selectedObject; // @synthesize selectedObject=_selectedObject;
@property(retain, nonatomic) NSArray *selectedObjects; // @synthesize selectedObjects=_selectedObjects;
@property(retain, nonatomic) NSArray *nextRespondingSidebarObjects; // @synthesize nextRespondingSidebarObjects;
@property(retain, nonatomic) GBRepositoriesController *repositoriesController; // @synthesize repositoriesController;
@property(retain, nonatomic) GBSidebarItem *sidebarItem; // @synthesize sidebarItem;
- (void)updateResponders;
- (id)commonPrefixForArrays:(id)arg1 ignoreFromEnd:(unsigned long long)arg2;
- (void)sidebarItemLoadContentsFromPropertyList:(id)arg1;
- (id)plistV13FromPlistV12:(id)arg1;
- (id)sidebarItemContentsPropertyList;
- (id)sidebarItemChildAtIndex:(long long)arg1;
- (long long)sidebarItemNumberOfChildren;
@property(readonly, nonatomic) NSArray *clickedOrSelectedObjects;
@property(readonly, nonatomic) NSArray *clickedOrSelectedSidebarItems;
@property(retain, nonatomic) GBSidebarItem *clickedSidebarItem; // @dynamic clickedSidebarItem;
@property(retain, nonatomic) NSArray *selectedItemIndexes; // @dynamic selectedItemIndexes;
@property(retain, nonatomic) GBSidebarItem *selectedSidebarItem; // @dynamic selectedSidebarItem;
@property(retain, nonatomic) NSArray *selectedSidebarItems; // @dynamic selectedSidebarItems;
- (void)setExternalNextResponder:(id)arg1;
- (id)externalNextResponder;
- (void)removeObjectsFromSelection:(id)arg1;
- (void)addObjectsToSelection:(id)arg1;
- (BOOL)syncSelectedObjects;
- (BOOL)openURLs:(id)arg1;
- (void)contentsDidChange;
- (id)staticResponders;
- (id)init;
- (void)dealloc;

@end

