//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "NSTextFieldDelegate-Protocol.h"

@class GBSearchBarTextField, NSProgressIndicator, NSString, NSTextField, NSView;
@protocol GBSearchBarControllerDelegate;

__attribute__((visibility("hidden")))
@interface GBSearchBarController : NSViewController <NSTextFieldDelegate>
{
    BOOL visible;
    BOOL spinning;
    double progress;
    NSView *contentView;
    id <GBSearchBarControllerDelegate> delegate;
    unsigned long long resultsCount;
    NSView *barView;
    GBSearchBarTextField *searchField;
    NSProgressIndicator *progressIndicator;
    NSTextField *statusLabel;
}

@property(nonatomic) NSTextField *statusLabel; // @synthesize statusLabel;
@property(retain, nonatomic) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator;
@property(retain, nonatomic) GBSearchBarTextField *searchField; // @synthesize searchField;
@property(retain, nonatomic) NSView *barView; // @synthesize barView;
@property(nonatomic) unsigned long long resultsCount; // @synthesize resultsCount;
@property(nonatomic) id <GBSearchBarControllerDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSView *contentView; // @synthesize contentView;
@property(nonatomic) double progress; // @synthesize progress;
@property(nonatomic) BOOL spinning; // @synthesize spinning;
@property(nonatomic) BOOL visible; // @synthesize visible;
- (void)updateStatusLabel;
- (void)setVisible:(BOOL)arg1 animated:(BOOL)arg2;
@property(copy, nonatomic) NSString *searchString; // @dynamic searchString;
- (void)unfocus;
- (void)focus;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)searchFieldDidChange:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;

@end

