//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class GBHistoryTask, GBRepository, GBSearchQuery, NSMutableArray, NSMutableSet;

__attribute__((visibility("hidden")))
@interface GBSearch : NSObject
{
    GBSearchQuery *query;
    GBRepository *repository;
    NSMutableArray *commits;
    id searchCache;
    id target;
    SEL action;
    NSMutableSet *commitIds;
    BOOL cancelled;
    GBHistoryTask *task;
    int lastTimestamp;
    BOOL isRunning;
    unsigned long long limit;
    BOOL usedCachedCommits;
}

+ (id)searchWithQuery:(id)arg1 repository:(id)arg2 target:(id)arg3 action:(SEL)arg4;
@property(nonatomic) BOOL usedCachedCommits; // @synthesize usedCachedCommits;
@property(nonatomic) unsigned long long limit; // @synthesize limit;
@property(nonatomic) BOOL isRunning; // @synthesize isRunning;
@property(nonatomic) int lastTimestamp; // @synthesize lastTimestamp;
@property(nonatomic) GBHistoryTask *task; // @synthesize task;
@property(nonatomic) BOOL cancelled; // @synthesize cancelled;
@property(retain, nonatomic) NSMutableSet *commitIds; // @synthesize commitIds;
@property(nonatomic) SEL action; // @synthesize action;
@property(nonatomic) id target; // @synthesize target;
@property(retain, nonatomic) id searchCache; // @synthesize searchCache;
@property(retain, nonatomic) NSMutableArray *commits; // @synthesize commits;
@property(retain, nonatomic) GBRepository *repository; // @synthesize repository;
@property(retain, nonatomic) GBSearchQuery *query; // @synthesize query;
- (void)launchNextTask;
- (void)processCommits:(id)arg1;
- (void)cancel;
- (void)start;
- (void)dealloc;

@end

