//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GBSearchBarController;

@protocol GBSearchBarControllerDelegate <NSObject>

@optional
- (void)searchBarControllerDidCancel:(GBSearchBarController *)arg1;
- (void)searchBarControllerDidChangeString:(GBSearchBarController *)arg1;
@end

