//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSResponder.h>

#import "NSPasteboardWriting-Protocol.h"

@class GBSidebarCell, GBSidebarController, NSImage, NSMenu, NSMutableDictionary, NSString;
@protocol GBSidebarItemObject;

__attribute__((visibility("hidden")))
@interface GBSidebarItem : NSResponder <NSPasteboardWriting>
{
    BOOL stopped;
    NSResponder<GBSidebarItemObject> *object;
    GBSidebarController *sidebarController;
    NSString *UID;
    NSImage *image;
    NSString *title;
    NSString *tooltip;
    unsigned long long badgeInteger;
    GBSidebarCell *cell;
    NSMenu *menu;
    NSMutableDictionary *_viewsDictionary;
    BOOL section;
    BOOL spinning;
    double progress;
    BOOL selectable;
    BOOL expandable;
    BOOL editable;
    BOOL draggable;
    BOOL collapsed;
}

@property(nonatomic, getter=isCollapsed) BOOL collapsed; // @synthesize collapsed;
@property(nonatomic, getter=isDraggable) BOOL draggable; // @synthesize draggable;
@property(nonatomic, getter=isEditable) BOOL editable; // @synthesize editable;
@property(nonatomic, getter=isExpandable) BOOL expandable; // @synthesize expandable;
@property(nonatomic, getter=isSelectable) BOOL selectable; // @synthesize selectable;
@property(nonatomic) double progress; // @synthesize progress;
@property(nonatomic, getter=isSpinning) BOOL spinning; // @synthesize spinning;
@property(nonatomic, getter=isSection) BOOL section; // @synthesize section;
@property(retain, nonatomic) NSMutableDictionary *viewsDictionary; // @synthesize viewsDictionary=_viewsDictionary;
@property(retain, nonatomic) NSMenu *menu; // @synthesize menu;
@property(retain, nonatomic) GBSidebarCell *cell; // @synthesize cell;
@property(nonatomic) unsigned long long badgeInteger; // @synthesize badgeInteger;
@property(copy, nonatomic) NSString *tooltip; // @synthesize tooltip;
@property(copy, nonatomic) NSString *title; // @synthesize title;
@property(retain, nonatomic) NSImage *image; // @synthesize image;
@property(copy, nonatomic) NSString *UID; // @synthesize UID;
@property(nonatomic) GBSidebarController *sidebarController; // @synthesize sidebarController;
@property(nonatomic) NSResponder<GBSidebarItemObject> *object; // @synthesize object;
- (id)pasteboardPropertyListForType:(id)arg1;
- (id)writableTypesForPasteboard:(id)arg1;
- (id)pathToItem:(id)arg1;
- (id)mutablePathToItem:(id)arg1;
- (id)parentOfItem:(id)arg1;
- (id)allChildren;
- (void)enumerateChildrenUsingBlock:(CDUnknownBlockType)arg1;
- (id)findItemWithUID:(id)arg1;
- (void)setStringValue:(id)arg1;
- (unsigned long long)indexOfChild:(id)arg1;
- (id)childAtIndex:(long long)arg1;
- (long long)numberOfChildren;
- (BOOL)isStopped;
- (void)stop;
- (void)update;
- (void)collapse;
- (void)expand;
- (void)edit;
- (BOOL)moveItems:(id)arg1 toIndex:(unsigned long long)arg2;
- (BOOL)openURLs:(id)arg1 atIndex:(unsigned long long)arg2;
- (unsigned long long)dragOperationForItems:(id)arg1 outlineView:(id)arg2;
- (unsigned long long)dragOperationForURLs:(id)arg1 outlineView:(id)arg2;
@property(nonatomic, getter=isExpanded) BOOL expanded; // @dynamic expanded;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)tryToPerform:(SEL)arg1 with:(id)arg2;
- (void)removeAllViews;
- (void)setView:(id)arg1 forKey:(id)arg2;
- (id)viewForKey:(id)arg1;
- (double)visibleProgress;
- (double)subtreeProgress;
- (BOOL)visibleSpinning;
- (BOOL)isSubtreeSpinning;
- (unsigned long long)visibleBadgeInteger;
- (unsigned long long)subtreeBadgeInteger;
- (id)description;
- (id)init;
- (void)dealloc;

@end

