//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

@class GBSidebarItem, GBSidebarOutlineView;

__attribute__((visibility("hidden")))
@interface GBSidebarCell : NSTextFieldCell
{
    GBSidebarItem *sidebarItem;
    GBSidebarOutlineView *outlineView;
    BOOL isForeground;
    BOOL isFocused;
    BOOL isDragged;
}

+ (double)cellHeight;
@property(nonatomic) BOOL isDragged; // @synthesize isDragged;
@property(nonatomic) BOOL isFocused; // @synthesize isFocused;
@property(nonatomic) BOOL isForeground; // @synthesize isForeground;
@property(nonatomic) GBSidebarOutlineView *outlineView; // @synthesize outlineView;
@property(nonatomic) GBSidebarItem *sidebarItem; // @synthesize sidebarItem;
- (struct CGRect)drawBadge:(id)arg1 inRect:(struct CGRect)arg2;
- (struct CGRect)drawBadgeIfNeededInRectAndReturnRemainingRect:(struct CGRect)arg1;
- (struct CGRect)drawSpinnerIfNeededInRectAndReturnRemainingRect:(struct CGRect)arg1;
- (struct CGRect)drawCocoaSpinnerIfNeededInRectAndReturnRemainingRect:(struct CGRect)arg1;
- (struct CGRect)drawCustomSpinnerIfNeededInRectAndReturnRemainingRect:(struct CGRect)arg1;
- (struct CGRect)drawIconAndReturnRemainingRect:(struct CGRect)arg1;
- (void)selectWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 start:(long long)arg5 length:(long long)arg6;
- (void)editWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 event:(id)arg5;
- (struct CGRect)editorFrameForSuggestedRect:(struct CGRect)arg1;
- (id)setUpFieldEditorAttributes:(id)arg1;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawTextInRect:(struct CGRect)arg1;
- (struct CGRect)drawExtraFeaturesAndReturnRemainingRect:(struct CGRect)arg1;
- (id)image;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithItem:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;
- (void)setupCell;

@end

