//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSCoding-Protocol.h"
#import "NSObject-Protocol.h"

@class GBSidebarItem, NSArray, NSImage, NSMenu, NSOutlineView, NSString;

@protocol GBSidebarItemObject <NSObject, NSCoding>
- (void)sidebarItemLoadContentsFromPropertyList:(id)arg1;
- (id)sidebarItemContentsPropertyList;
- (GBSidebarItem *)sidebarItem;

@optional
- (BOOL)sidebarItemMoveObjects:(NSArray *)arg1 toIndex:(unsigned long long)arg2;
- (BOOL)sidebarItemOpenURLs:(NSArray *)arg1 atIndex:(unsigned long long)arg2;
- (NSMenu *)sidebarItemMenu;
- (unsigned long long)sidebarItemDragOperationForItems:(NSArray *)arg1 outlineView:(NSOutlineView *)arg2;
- (unsigned long long)sidebarItemDragOperationForURLs:(NSArray *)arg1 outlineView:(NSOutlineView *)arg2;
- (void)sidebarItemSetStringValue:(NSString *)arg1;
- (double)sidebarItemProgress;
- (BOOL)sidebarItemIsSpinning;
- (BOOL)sidebarItemIsDraggable;
- (BOOL)sidebarItemIsEditable;
- (BOOL)sidebarItemIsExpandable;
- (BOOL)sidebarItemIsSelectable;
- (unsigned long long)sidebarItemBadgeInteger;
- (NSString *)sidebarItemTooltip;
- (NSString *)sidebarItemTitle;
- (NSImage *)sidebarItemImage;
- (GBSidebarItem *)sidebarItemChildAtIndex:(long long)arg1;
- (long long)sidebarItemNumberOfChildren;
@end

