//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "NSMenuDelegate-Protocol.h"
#import "NSOutlineViewDataSource-Protocol.h"
#import "NSOutlineViewDelegate-Protocol.h"

@class GBRootController, GBSidebarItem, NSButton, NSOutlineView, OAFastJumpController;

__attribute__((visibility("hidden")))
@interface GBSidebarController : NSViewController <NSMenuDelegate, NSOutlineViewDataSource, NSOutlineViewDelegate>
{
    GBRootController *rootController;
    NSOutlineView *outlineView;
    unsigned long long ignoreSelectionChange;
    NSButton *buyButton;
    OAFastJumpController *jumpController;
}

@property(retain, nonatomic) OAFastJumpController *jumpController; // @synthesize jumpController;
@property(retain, nonatomic) NSButton *buyButton; // @synthesize buyButton;
@property(nonatomic) unsigned long long ignoreSelectionChange; // @synthesize ignoreSelectionChange;
@property(retain, nonatomic) NSOutlineView *outlineView; // @synthesize outlineView;
@property(retain, nonatomic) GBRootController *rootController; // @synthesize rootController;
- (void)updateBuyButton;
- (void)updateExpandedState;
- (void)updateSelection;
- (void)updateContents;
- (void)updateItem:(id)arg1;
- (void)collapseItem:(id)arg1;
- (void)expandItem:(id)arg1;
- (void)editItem:(id)arg1;
- (BOOL)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;
- (unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (id)outlineView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 item:(id)arg5 mouseLocation:(struct CGPoint)arg6;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isGroupItem:(id)arg2;
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewItemDidExpand:(id)arg1;
- (BOOL)control:(id)arg1 textShouldEndEditing:(id)arg2;
- (BOOL)control:(id)arg1 textShouldBeginEditing:(id)arg2;
- (void)outlineView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 byItem:(id)arg4;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (void)menuDidClose:(id)arg1;
- (void)menuWillOpen:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)selectNextItem:(id)arg1;
- (void)selectPreviousItem:(id)arg1;
- (void)selectItemWithDirection:(long long)arg1;
- (id)firstSelectableRowStartingAtRow:(long long)arg1 direction:(long long)arg2;
- (BOOL)validateSelectRightPane:(id)arg1;
- (void)selectPane:(id)arg1;
- (void)selectRightPane:(id)arg1;
- (void)rootControllerDidChangeSelection:(id)arg1;
- (void)rootControllerDidChangeContents:(id)arg1;
- (id)defaultMenu;
- (id)selectedSidebarItems;
@property(readonly, nonatomic) GBSidebarItem *clickedSidebarItem;
- (void)licenseDidUpdate:(id)arg1;
- (void)loadView;
- (void)dealloc;

@end

