//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBBaseChangesController.h"
#import "GBChangeDelegate-Protocol.h"

@class GBCellWithView, GBCommitPromptController, GBStage, GBStageHeaderAnimation, GBStageMessageHistoryController, GBStageShortcutHintDetector, NSButton, NSIndexSet, NSTextField, NSTextView, NSUndoManager;

__attribute__((visibility("hidden")))
@interface GBStageViewController : GBBaseChangesController <GBChangeDelegate, NSTextFieldDelegate, NSTextViewDelegate, NSAnimationDelegate>
{
    NSTextView *messageTextView;
    NSButton *commitButton;
    GBCommitPromptController *commitPromptController;
    NSIndexSet *rememberedSelectionIndexes;
    GBStageHeaderAnimation *headerAnimation;
    GBCellWithView *headerCell;
    NSTextField *shortcutHintLabel;
    GBStageShortcutHintDetector *shortcutHintDetector;
    GBStageMessageHistoryController *messageHistoryController;
    NSUndoManager *textViewUndoManager;
    NSTextField *rebaseStatusLabel;
    NSButton *rebaseCancelButton;
    NSButton *rebaseSkipButton;
    NSButton *rebaseContinueButton;
    BOOL alreadyValidatedUserNameAndEmail;
    double overridenHeaderHeight;
}

@property(nonatomic) double overridenHeaderHeight; // @synthesize overridenHeaderHeight;
@property(nonatomic) BOOL alreadyValidatedUserNameAndEmail; // @synthesize alreadyValidatedUserNameAndEmail;
@property(retain, nonatomic) NSButton *rebaseContinueButton; // @synthesize rebaseContinueButton;
@property(retain, nonatomic) NSButton *rebaseSkipButton; // @synthesize rebaseSkipButton;
@property(retain, nonatomic) NSButton *rebaseCancelButton; // @synthesize rebaseCancelButton;
@property(retain, nonatomic) NSTextField *rebaseStatusLabel; // @synthesize rebaseStatusLabel;
@property(retain, nonatomic) NSUndoManager *textViewUndoManager; // @synthesize textViewUndoManager;
@property(retain, nonatomic) GBStageMessageHistoryController *messageHistoryController; // @synthesize messageHistoryController;
@property(retain, nonatomic) GBStageShortcutHintDetector *shortcutHintDetector; // @synthesize shortcutHintDetector;
@property(retain, nonatomic) NSTextField *shortcutHintLabel; // @synthesize shortcutHintLabel;
@property(retain, nonatomic) GBCellWithView *headerCell; // @synthesize headerCell;
@property(retain, nonatomic) GBStageHeaderAnimation *headerAnimation; // @synthesize headerAnimation;
@property(retain, nonatomic) NSIndexSet *rememberedSelectionIndexes; // @synthesize rememberedSelectionIndexes;
@property(retain, nonatomic) GBCommitPromptController *commitPromptController; // @synthesize commitPromptController;
@property(retain, nonatomic) NSButton *commitButton; // @synthesize commitButton;
@property(retain, nonatomic) NSTextView *messageTextView; // @synthesize messageTextView;
- (void)resetMessageHistory;
- (void)validateUserNameAndEmailIfNeededWithBlock:(id)arg1;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (BOOL)tableView:(id)arg1 shouldTrackCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)updateCommitButtonEnabledState;
- (BOOL)isEditingCommitMessage;
- (BOOL)validateSelectLeftPane:(id)arg1;
- (void)updateHeaderSizeAnimating:(BOOL)arg1;
- (void)updateHeader;
- (void)syncHeaderAfterLeaving;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textDidChange:(id)arg1;
- (void)textView:(id)arg1 didCancel:(id)arg2;
- (void)textView:(id)arg1 willResignFirstResponder:(BOOL)arg2;
- (void)textView:(id)arg1 willBecomeFirstResponder:(BOOL)arg2;
- (id)undoManagerForTextView:(id)arg1;
- (void)doubleClickChange:(id)arg1;
- (void)unstageChange:(id)arg1;
- (void)stageChange:(id)arg1;
- (void)updateViews;
@property(readonly, nonatomic) GBStage *stage; // @dynamic stage;
- (void)nextMessage:(id)arg1;
- (void)previousMessage:(id)arg1;
- (BOOL)validateBranch;
- (id)validCommitMessage;
- (BOOL)validateReallyCommit:(id)arg1;
- (void)reallyCommit:(id)arg1;
- (void)reallyReallyCommit;
- (BOOL)validateCommit:(id)arg1;
- (void)commit:(id)arg1;
- (void)commitWithSheet:(id)arg1;
- (BOOL)validateStageDeleteFile:(id)arg1;
- (void)stageDeleteFile:(id)arg1;
- (BOOL)validateStageRevertFile:(id)arg1;
- (void)stageRevertFile:(id)arg1;
- (BOOL)validateStageIgnoreFile:(id)arg1;
- (void)stageIgnoreFile:(id)arg1;
- (BOOL)validateStageDoStageUnstage:(id)arg1;
- (void)stageDoStageUnstage:(id)arg1;
- (BOOL)validateStageDoUnstage:(id)arg1;
- (void)stageDoUnstage:(id)arg1;
- (BOOL)validateStageDoStage:(id)arg1;
- (void)stageDoStage:(id)arg1;
- (BOOL)validateStageAll:(id)arg1;
- (void)stageAll:(id)arg1;
- (void)repositoryControllerDidUpdateStage:(id)arg1;
- (void)loadView;
- (void)setChanges:(id)arg1;
- (double)headerHeight;
- (void)setRepositoryController:(id)arg1;
- (void)dealloc;

@end

