//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBTask.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface GBStashListTask : GBTask
{
    NSArray *stashes;
}

@property(retain, nonatomic) NSArray *stashes; // @synthesize stashes;
- (void)didFinishInBackground;
- (id)stashesFromStatusOutput:(id)arg1;
- (id)arguments;
- (void)dealloc;

@end

