//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class GBRepository, NSString, NSTextView;

__attribute__((visibility("hidden")))
@interface GBStageMessageHistoryController : NSObject
{
    GBRepository *repository;
    NSTextView *textView;
    NSString *initialMessage;
    NSString *email;
    long long messageIndex;
}

@property(nonatomic) long long messageIndex; // @synthesize messageIndex;
@property(copy, nonatomic) NSString *email; // @synthesize email;
@property(copy, nonatomic) NSString *initialMessage; // @synthesize initialMessage;
@property(retain, nonatomic) NSTextView *textView; // @synthesize textView;
@property(retain, nonatomic) GBRepository *repository; // @synthesize repository;
- (id)previousMessage;
- (id)nextMessage;
- (id)init;
- (void)dealloc;

@end

