//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBSidebarCell.h"

@class GBSubmodule;

__attribute__((visibility("hidden")))
@interface GBSubmoduleCell : GBSidebarCell
{
}

@property(readonly, nonatomic) GBSubmodule *submodule;
- (struct CGRect)drawButtonAndReturnRemainingRect:(struct CGRect)arg1 title:(id)arg2 key:(id)arg3 action:(SEL)arg4;
- (struct CGRect)drawExtraFeaturesAndReturnRemainingRect:(struct CGRect)arg1;
- (id)image;

@end

