//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSResponder.h>

#import "GBMainWindowItem-Protocol.h"
#import "GBSidebarItemObject-Protocol.h"

@class GBAuthenticatedTask, GBRepositoryController, GBSidebarItem, GBSubmodule, GBSubmoduleCloningViewController, NSError, NSString;

__attribute__((visibility("hidden")))
@interface GBSubmoduleCloningController : NSResponder <GBMainWindowItem, GBSidebarItemObject>
{
    GBSubmodule *_submodule;
    GBRepositoryController *_parentRepositoryController;
    GBSubmoduleCloningViewController *viewController;
    GBAuthenticatedTask *task;
    NSError *error;
    long long isDisabled;
    long long isSpinning;
    double sidebarItemProgress;
    NSString *progressStatus;
    GBSidebarItem *sidebarItem;
}

@property(retain, nonatomic) GBSidebarItem *sidebarItem; // @synthesize sidebarItem;
@property(copy, nonatomic) NSString *progressStatus; // @synthesize progressStatus;
@property(nonatomic) double sidebarItemProgress; // @synthesize sidebarItemProgress;
@property(nonatomic) long long isSpinning; // @synthesize isSpinning;
@property(nonatomic) long long isDisabled; // @synthesize isDisabled;
@property(retain, nonatomic) NSError *error; // @synthesize error;
@property(retain, nonatomic) GBAuthenticatedTask *task; // @synthesize task;
@property(retain, nonatomic) GBSubmoduleCloningViewController *viewController; // @synthesize viewController;
@property(nonatomic) GBRepositoryController *parentRepositoryController; // @synthesize parentRepositoryController=_parentRepositoryController;
@property(retain, nonatomic) GBSubmodule *submodule; // @synthesize submodule=_submodule;
- (id)pasteboardPropertyListForType:(id)arg1;
- (id)writableTypesForPasteboard:(id)arg1;
- (void)sidebarItemLoadContentsFromPropertyList:(id)arg1;
- (id)sidebarItemContentsPropertyList;
- (id)sidebarItemChildAtIndex:(long long)arg1;
- (long long)sidebarItemNumberOfChildren;
- (BOOL)sidebarItemIsExpandable;
- (BOOL)sidebarItemIsSpinning;
- (id)sidebarItemTooltip;
- (id)sidebarItemTitle;
- (void)didSelectWindowItem;
- (id)windowRepresentedURL;
- (id)windowTitle;
- (void)stop;
- (void)start;
- (void)cancelDownload:(id)arg1;
- (void)startDownload:(id)arg1;
- (id)remoteURL;
- (BOOL)isStarted;
- (id)initWithSubmodule:(id)arg1;
- (void)dealloc;

@end

