//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class GBSubmoduleCloningController, NSButton, NSProgressIndicator, NSTextField;

__attribute__((visibility("hidden")))
@interface GBSubmoduleCloningViewController : NSViewController
{
    NSTextField *messageLabel;
    NSTextField *errorLabel;
    NSButton *startButton;
    NSButton *cancelButton;
    NSProgressIndicator *progressIndicator;
    GBSubmoduleCloningController *repositoryController;
}

@property(nonatomic) GBSubmoduleCloningController *repositoryController; // @synthesize repositoryController;
@property(nonatomic) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator;
@property(nonatomic) NSButton *cancelButton; // @synthesize cancelButton;
@property(nonatomic) NSButton *startButton; // @synthesize startButton;
@property(nonatomic) NSTextField *errorLabel; // @synthesize errorLabel;
@property(nonatomic) NSTextField *messageLabel; // @synthesize messageLabel;
- (void)submoduleCloningControllerDidFinish:(id)arg1;
- (void)submoduleCloningControllerDidCancel:(id)arg1;
- (void)submoduleCloningControllerDidFail:(id)arg1;
- (void)submoduleCloningControllerProgress:(id)arg1;
- (void)submoduleCloningControllerDidStart:(id)arg1;
- (void)update;
- (void)loadView;
- (void)dealloc;

@end

