//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "OATask.h"

@class GBRepository;

__attribute__((visibility("hidden")))
@interface GBTask : OATask
{
    GBRepository *repository;
    BOOL ignoreMissingRepository;
}

+ (id)pathToBundledBinary:(id)arg1;
+ (id)bundledGitVersion;
+ (BOOL)isSnowLeopard;
+ (id)taskWithRepository:(id)arg1;
@property(nonatomic) BOOL ignoreMissingRepository; // @synthesize ignoreMissingRepository;
@property(nonatomic) GBRepository *repository; // @synthesize repository;
- (void)willLaunchTask;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

