//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSResponder.h>

#import "NSToolbarDelegate-Protocol.h"

@class NSToolbar, NSToolbarItem, NSWindow;

__attribute__((visibility("hidden")))
@interface GBToolbarController : NSResponder <NSToolbarDelegate>
{
    NSToolbar *toolbar;
    NSWindow *window;
    double sidebarWidth;
}

@property(nonatomic) double sidebarWidth; // @synthesize sidebarWidth;
@property(retain, nonatomic) NSWindow *window; // @synthesize window;
@property(retain, nonatomic) NSToolbar *toolbar; // @synthesize toolbar;
- (double)sidebarPadding;
- (void)updateAlignment;
- (void)update;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)removeAdditionalItems;
- (void)replaceItemWithIdentifier:(id)arg1 withItemWithIdentifier:(id)arg2;
- (void)removeItemWithIdentifier:(id)arg1;
- (long long)indexOfItemWithIdentifier:(id)arg1;
- (void)appendItemWithIdentifier:(id)arg1;
- (id)toolbarItemForIdentifier:(id)arg1;
- (void)didEndSheet:(id)arg1;
@property(readonly, nonatomic) NSToolbarItem *sidebarPaddingItem; // @dynamic sidebarPaddingItem;
- (void)dealloc;

@end

