//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBChangesBaseTask.h"

__attribute__((visibility("hidden")))
@interface GBUntrackedChangesTask : GBChangesBaseTask
{
}

- (id)changesFromDiffOutput:(id)arg1;
- (id)arguments;

@end

