//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBBasePromptController.h"

@class NSString, NSTextField;

__attribute__((visibility("hidden")))
@interface GBUserNameEmailController : GBBasePromptController
{
    NSString *userName;
    NSString *userEmail;
    NSTextField *nameField;
    NSTextField *emailField;
}

@property(retain) NSTextField *emailField; // @synthesize emailField;
@property(retain) NSTextField *nameField; // @synthesize nameField;
@property(retain) NSString *userEmail; // @synthesize userEmail;
@property(retain) NSString *userName; // @synthesize userName;
- (void)windowDidResignKey:(id)arg1;
- (void)updateWindow;
- (void)fillWithAddressBookData;
- (void)onOK:(id)arg1;
- (void)dealloc;

@end

