//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSCache, OAHTTPQueue;

__attribute__((visibility("hidden")))
@interface GBUserpicController : NSObject
{
    NSCache *cache;
    OAHTTPQueue *httpQueue;
}

@property(retain, nonatomic) OAHTTPQueue *httpQueue; // @synthesize httpQueue;
@property(retain, nonatomic) NSCache *cache; // @synthesize cache;
- (void)removeCachedImages;
- (void)cancel;
- (void)loadImageForEmail:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (id)imageForEmail:(id)arg1;
- (id)init;
- (void)dealloc;

@end

