//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface GBVersionComparator : NSObject
{
}

+ (id)defaultComparator;
- (long long)compareVersion:(id)arg1 toVersion:(id)arg2;
- (id)splitVersionString:(id)arg1;
- (int)typeOfCharacter:(id)arg1;

@end

