//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "GBWindowControllerWithCallback.h"

#import "NSWindowDelegate-Protocol.h"

__attribute__((visibility("hidden")))
@interface GBWelcomeController : GBWindowControllerWithCallback <NSWindowDelegate>
{
}

- (void)cancel:(id)arg1;
- (void)open:(id)arg1;
- (void)clone:(id)arg1;

@end

