//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

__attribute__((visibility("hidden")))
@interface GBWindowControllerWithCallback : NSWindowController
{
    CDUnknownBlockType completionHandler;
}

@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler;
- (void)presentSheetInMainWindowSilent:(BOOL)arg1;
- (void)presentSheetInMainWindow;
- (void)performCompletionHandler:(BOOL)arg1;
- (void)dealloc;

@end

