//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface GitConfig : NSObject
{
    struct git_config *config;
}

@property(nonatomic) struct git_config *config; // @synthesize config;
- (void)enumerateKeysAndObjectsUsingBlock:(CDUnknownBlockType)arg1;
- (void)removeKey:(id)arg1;
- (void)setString:(id)arg1 forKey:(id)arg2;
- (id)stringForKey:(id)arg1;
- (void)dealloc;
- (void)close;
- (id)initWithURL:(id)arg1;
- (id)initWithRepositoryURL:(id)arg1;
- (id)initGlobalConfig;
- (id)userConfigURL;

@end

