//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSString, NSURL;
@protocol iRateDelegate;

__attribute__((visibility("hidden")))
@interface iRate : NSObject
{
    unsigned long long appStoreID;
    NSString *applicationName;
    NSString *applicationVersion;
    float daysUntilPrompt;
    unsigned long long usesUntilPrompt;
    unsigned long long eventsUntilPrompt;
    float remindPeriod;
    NSString *messageTitle;
    NSString *message;
    NSString *cancelButtonLabel;
    NSString *remindButtonLabel;
    NSString *rateButtonLabel;
    NSURL *ratingsURL;
    BOOL disabled;
    BOOL debug;
    id <iRateDelegate> delegate;
}

+ (id)sharedInstance;
@property(nonatomic) id <iRateDelegate> delegate; // @synthesize delegate;
@property(nonatomic) BOOL debug; // @synthesize debug;
@property(nonatomic) BOOL disabled; // @synthesize disabled;
@property(retain, nonatomic) NSURL *ratingsURL; // @synthesize ratingsURL;
@property(copy, nonatomic) NSString *rateButtonLabel; // @synthesize rateButtonLabel;
@property(copy, nonatomic) NSString *remindButtonLabel; // @synthesize remindButtonLabel;
@property(copy, nonatomic) NSString *cancelButtonLabel; // @synthesize cancelButtonLabel;
@property(copy, nonatomic) NSString *message; // @synthesize message;
@property(copy, nonatomic) NSString *messageTitle; // @synthesize messageTitle;
@property(nonatomic) float remindPeriod; // @synthesize remindPeriod;
@property(nonatomic) unsigned long long eventsUntilPrompt; // @synthesize eventsUntilPrompt;
@property(nonatomic) unsigned long long usesUntilPrompt; // @synthesize usesUntilPrompt;
@property(nonatomic) float daysUntilPrompt; // @synthesize daysUntilPrompt;
@property(retain, nonatomic) NSString *applicationVersion; // @synthesize applicationVersion;
@property(copy, nonatomic) NSString *applicationName; // @synthesize applicationName;
@property(nonatomic) unsigned long long appStoreID; // @synthesize appStoreID;
- (void)logEvent:(BOOL)arg1;
- (void)alertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)openRatingsPageInAppStore;
- (void)openAppPageWhenAppStoreLaunched;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationLaunched:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)promptIfNetworkAvailable;
- (void)promptForRating;
- (BOOL)shouldPromptForRating;
- (void)incrementEventCount;
- (void)incrementUseCount;
- (void)dealloc;
@property(nonatomic) BOOL ratedThisVersion;
@property(nonatomic) BOOL declinedThisVersion;
@property(nonatomic) unsigned long long eventCount;
@property(nonatomic) unsigned long long usesCount;
@property(retain, nonatomic) NSDate *lastReminded;
@property(retain, nonatomic) NSDate *firstUsed;
- (id)init;

@end

