//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (OAArrayHelpers)
- (id)arrayOfChunksBySize:(unsigned long long)arg1;
- (id)mapWithBlock:(CDUnknownBlockType)arg1;
- (id)objectWithValue:(id)arg1 forKeyPath:(id)arg2;
- (id)objectWithValue:(id)arg1 forKey:(id)arg2;
- (BOOL)allAreTrue:(SEL)arg1;
- (BOOL)anyIsTrue:(SEL)arg1;
- (id)objectAtIndex:(unsigned long long)arg1 or:(id)arg2;
- (id)reversedArray;
- (id)firstObject;
@end

