//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSAttributedString.h>

@interface NSAttributedString (OAAttributedStringHelpers)
+ (id)attributedStringWithString:(id)arg1 attributes:(id)arg2 highlightedRanges:(id)arg3 highlightColor:(id)arg4;
+ (id)attributedStringWithString:(id)arg1 attributes:(id)arg2;
+ (id)attributedStringWithString:(id)arg1;
@end

