//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSFileManager.h>

@interface NSFileManager (OAFileManagerHelpers)
+ (void)calculateSizeAtURL:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (id)contentsOfDirectoryAtURL:(id)arg1;
+ (BOOL)isWritableDirectoryAtPath:(id)arg1;
+ (BOOL)isReadableDirectoryAtPath:(id)arg1;
- (void)writeData:(id)arg1 toPath:(id)arg2;
- (void)createFolderForFilePath:(id)arg1;
- (void)createFolderForPath:(id)arg1;
- (id)contentsOfDirectoryAtURL:(id)arg1;
- (BOOL)isWritableDirectoryAtPath:(id)arg1;
- (BOOL)isReadableDirectoryAtPath:(id)arg1;
@end

