//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSMutableAttributedString.h>

@interface NSMutableAttributedString (OAAttributedStringHelpers)
- (void)removeAttribute:(id)arg1 fromSubstring:(id)arg2;
- (void)addAttributes:(id)arg1 toSubstring:(id)arg2;
- (void)addAttribute:(id)arg1 value:(id)arg2 substring:(id)arg3;
- (void)updateAttribute:(id)arg1 inRange:(struct _NSRange)arg2 withBlock:(CDUnknownBlockType)arg3;
- (void)updateAttribute:(id)arg1 forSubstring:(id)arg2 withBlock:(CDUnknownBlockType)arg3;
@end

