//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface NSObject (OAPerformBlockAfterDelay)
+ (void)cancelPreviousPerformBlock:(id)arg1;
+ (id)performBlock:(CDUnknownBlockType)arg1 afterDelay:(double)arg2;
@end

