//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "OAPropertyListRepresentation-Protocol.h"

@interface NSObject (OAPropertyListRepresentation) <OAPropertyListRepresentation>
- (void)OALoadContentsFromPropertyList:(id)arg1;
- (id)OAContentsPropertyList;
@end

