//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface NSObject (OASelectorNotifications)
+ (void)removeObserver:(id)arg1 forSelector:(SEL)arg2;
+ (void)addObserver:(id)arg1 forSelector:(SEL)arg2;
+ (id)OANotificationNameForSelector:(SEL)arg1;
- (void)removeObserverForAllSelectors:(id)arg1;
- (void)addObserverForAllSelectors:(id)arg1;
- (void)removeObserver:(id)arg1 forSelector:(SEL)arg2;
- (void)addObserver:(id)arg1 forSelector:(SEL)arg2;
- (void)notifyWithSelector:(SEL)arg1 withObject:(id)arg2;
- (void)notifyWithSelector:(SEL)arg1;
- (void)OADispatchSelectorNotification:(id)arg1;
- (id)OANotificationNameForSelector:(SEL)arg1;
@end

