//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (OAStringHelpers)
- (id)stringByAddingAllPercentEscapesUsingEncoding:(unsigned long long)arg1;
- (id)prettyTrimmedStringToLength:(unsigned long long)arg1;
- (id)trimmedStringToLength:(unsigned long long)arg1;
- (id)stringByAppendingEllipsis;
- (id)md5hexdigest;
- (id)pathWithSuffix:(id)arg1;
- (id)relativePathToDirectoryPath:(id)arg1;
- (id)commonPrefixWithPath:(id)arg1;
- (id)twoLastPathComponentsWithDash;
- (id)twoLastPathComponentsWithSlash;
- (id)stringWithFirstLetterCapitalized;
- (BOOL)isEmptyString;
- (id)uniqueStringForStrings:(id)arg1;
- (id)uniqueStringForStrings:(id)arg1 appendingFormat:(id)arg2;
@end

