//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSWindow.h>

@interface NSWindow (OAWindowControllerHelpers)
- (void)endSheetForController:(id)arg1;
- (void)beginSheetForController:(id)arg1;
@end

