//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface OAActivityIndicator : NSObject
{
    long long count;
    BOOL value;
}

+ (BOOL)isActive;
+ (void)pop;
+ (void)push;
+ (id)sharedIndicator;
@property(nonatomic) BOOL value; // @synthesize value;
- (BOOL)isActive;
- (void)pop;
- (void)push;
- (void)updateValueOnMainThread:(BOOL)arg1;

@end

