//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface OABlockTransaction : NSObject
{
    BOOL stageTransactionInProgress;
    CDUnknownBlockType transactionPendingBlock;
}

@property(retain, nonatomic) CDUnknownBlockType transactionPendingBlock; // @synthesize transactionPendingBlock;
- (void)clean;
- (void)end;
- (void)begin:(CDUnknownBlockType)arg1;
- (void)dealloc;

@end

