//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSMutableSet;

__attribute__((visibility("hidden")))
@interface OABlockMerger : NSObject
{
    NSMutableDictionary *completionHandlersByTaskNames;
    NSMutableSet *ranTaskNames;
}

@property(retain, nonatomic) NSMutableSet *ranTaskNames; // @synthesize ranTaskNames;
@property(retain, nonatomic) NSMutableDictionary *completionHandlersByTaskNames; // @synthesize completionHandlersByTaskNames;
- (void)didFinishTask:(id)arg1;
- (void)performTaskOnce:(id)arg1 withBlock:(CDUnknownBlockType)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)performTask:(id)arg1 withBlock:(CDUnknownBlockType)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)init;
- (void)dealloc;

@end

