//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface OABlockTable : NSObject
{
    NSMutableDictionary *table;
    NSMutableDictionary *tableCounters;
}

+ (id)description;
+ (void)addBlock:(CDUnknownBlockType)arg1 forName:(id)arg2 proceedIfClear:(CDUnknownBlockType)arg3;
+ (void)callBlockForName:(id)arg1;
+ (void)addBlock:(CDUnknownBlockType)arg1 forName:(id)arg2;
+ (BOOL)containsBlockForName:(id)arg1;
+ (id)sharedTable;
@property(retain, nonatomic) NSMutableDictionary *tableCounters; // @synthesize tableCounters;
@property(retain, nonatomic) NSMutableDictionary *table; // @synthesize table;
- (id)description;
- (void)addBlock:(CDUnknownBlockType)arg1 forName:(id)arg2 proceedIfClear:(CDUnknownBlockType)arg3;
- (void)callBlockForName:(id)arg1;
- (void)addBlock:(CDUnknownBlockType)arg1 forName:(id)arg2;
- (BOOL)containsBlockForName:(id)arg1;
- (void)dealloc;
- (id)init;

@end

