//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface OAFastJumpController : NSObject
{
    CDUnknownBlockType delayedBlock;
    BOOL isJumping;
    double flushInterval;
}

+ (id)controller;
@property(nonatomic) double flushInterval; // @synthesize flushInterval;
@property(nonatomic) BOOL isJumping; // @synthesize isJumping;
@property(copy, nonatomic) CDUnknownBlockType delayedBlock; // @synthesize delayedBlock;
- (void)callBlockAndClear;
- (void)regularCheck;
- (void)delayedCheck;
- (void)flush;
- (void)cancel;
- (void)delayBlockIfNeeded:(CDUnknownBlockType)arg1;
- (void)dealloc;

@end

