//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface OAFSEvent : NSObject
{
    NSString *path;
    unsigned int flags;
    unsigned long long eventId;
}

+ (id)eventWithPath:(id)arg1 flags:(unsigned int)arg2 eventId:(unsigned long long)arg3;
@property(nonatomic) unsigned long long eventId; // @synthesize eventId;
@property(nonatomic) unsigned int flags; // @synthesize flags;
@property(copy, nonatomic) NSString *path; // @synthesize path;
- (id)description;
- (BOOL)containedInFolder:(id)arg1;
- (id)flagsDescription;
- (void)dealloc;

@end

