//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSCountedSet;

__attribute__((visibility("hidden")))
@interface OAFSEventStream : NSObject
{
    struct __FSEventStream *streamRef;
    double latency;
    BOOL watchRoot;
    BOOL ignoreSelf;
    NSCountedSet *pathsBag;
    BOOL started;
    BOOL enabled;
}

@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled;
@property(nonatomic) BOOL started; // @synthesize started;
@property(retain, nonatomic) NSCountedSet *pathsBag; // @synthesize pathsBag;
@property(nonatomic) BOOL ignoreSelf; // @synthesize ignoreSelf;
@property(nonatomic) BOOL watchRoot; // @synthesize watchRoot;
@property(nonatomic) double latency; // @synthesize latency;
@property(nonatomic) struct __FSEventStream *streamRef; // @synthesize streamRef;
- (void)didReceiveEvents:(id)arg1;
- (void)stop;
- (void)start;
- (void)update;
- (id)description;
- (void)flushEvents;
- (void)removePath:(id)arg1;
- (void)addPath:(id)arg1;
@property(readonly, nonatomic) NSArray *paths; // @dynamic paths;
- (id)init;
- (void)dealloc;

@end

