//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSURLConnectionDelegate-Protocol.h"

@class NSArray, NSData, NSError, NSFileHandle, NSHTTPURLResponse, NSMutableData, NSMutableDictionary, NSString, NSURL, NSURLConnection, NSURLRequest;
@protocol OAHTTPDownloadDelegate;

__attribute__((visibility("hidden")))
@interface OAHTTPDownload : NSObject <NSURLConnectionDelegate, NSCoding>
{
    NSURLRequest *request;
    NSURL *url;
    NSString *username;
    NSString *password;
    NSArray *allowedContentTypes;
    NSURLConnection *connection;
    NSData *data;
    NSHTTPURLResponse *lastResponse;
    NSError *error;
    CDUnknownBlockType block;
    CDUnknownBlockType completionBlock;
    NSString *runLoopMode;
    NSURL *targetFileURL;
    NSMutableData *receivedData;
    NSFileHandle *fileHandleForWriting;
    NSMutableDictionary *userDictionary;
    unsigned long long byteOffset;
    BOOL doNotShowActivityIndicator;
    NSObject<OAHTTPDownloadDelegate> *delegate;
    BOOL alreadyStarted;
}

+ (id)downloadWithRequest:(id)arg1 delegate:(id)arg2;
+ (id)downloadWithURL:(id)arg1 delegate:(id)arg2;
+ (id)downloadWithRequest:(id)arg1;
+ (id)downloadWithURL:(id)arg1;
+ (id)download;
@property(nonatomic) BOOL alreadyStarted; // @synthesize alreadyStarted;
@property(nonatomic) NSObject<OAHTTPDownloadDelegate> *delegate; // @synthesize delegate;
@property(nonatomic) BOOL doNotShowActivityIndicator; // @synthesize doNotShowActivityIndicator;
@property(nonatomic) unsigned long long byteOffset; // @synthesize byteOffset;
@property(retain, nonatomic) NSMutableDictionary *userDictionary; // @synthesize userDictionary;
@property(retain, nonatomic) NSFileHandle *fileHandleForWriting; // @synthesize fileHandleForWriting;
@property(retain, nonatomic) NSMutableData *receivedData; // @synthesize receivedData;
@property(copy, nonatomic) NSURL *targetFileURL; // @synthesize targetFileURL;
@property(copy, nonatomic) NSString *runLoopMode; // @synthesize runLoopMode;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block;
@property(retain, nonatomic) NSError *error; // @synthesize error;
@property(retain, nonatomic) NSHTTPURLResponse *lastResponse; // @synthesize lastResponse;
@property(retain, nonatomic) NSData *data; // @synthesize data;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection;
@property(copy, nonatomic) NSArray *allowedContentTypes; // @synthesize allowedContentTypes;
@property(copy, nonatomic) NSString *password; // @synthesize password;
@property(copy, nonatomic) NSString *username; // @synthesize username;
@property(copy, nonatomic) NSURL *url; // @synthesize url;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request;
- (void)resetFileHandle;
- (void)prepareFileHandleIfNeeded;
- (void)logError:(id)arg1;
- (void)log:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (BOOL)connectionShouldUseCredentialStorage:(id)arg1;
- (void)connection:(id)arg1 didCancelAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (BOOL)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2;
- (id)connection:(id)arg1 needNewBodyStream:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (id)willCacheResponse:(id)arg1;
- (void)didComplete;
- (void)didFailWithError:(id)arg1;
- (void)didFinishLoading;
- (void)didSendBodyData:(long long)arg1 totalBytesWritten:(long long)arg2 totalBytesExpectedToWrite:(long long)arg3;
- (void)didReceiveData:(id)arg1;
- (void)didReceiveResponse:(id)arg1;
- (BOOL)shouldUseCredentialStorage;
- (void)didCancelAuthenticationChallenge:(id)arg1;
- (void)didReceiveAuthenticationChallenge:(id)arg1;
- (BOOL)canAuthenticateAgainstProtectionSpace:(id)arg1;
- (id)needNewBodyStream:(id)arg1;
- (id)willSendRequest:(id)arg1 redirectResponse:(id)arg2;
- (float)loadingProgress;
- (BOOL)isCancelled;
- (void)cancel;
- (void)startWithBlock:(CDUnknownBlockType)arg1;
- (void)start;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (id)init;
- (void)dealloc;

@end

