//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface OAKeyValueObservingListener : NSObject
{
    id observer;
    id target;
    NSString *keyPath;
    SEL selector;
    SEL selectorWithNewValue;
    SEL selectorWithoutArguments;
    id userInfo;
    unsigned long long options;
}

@property(nonatomic) unsigned long long options; // @synthesize options;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo;
@property(nonatomic) SEL selectorWithoutArguments; // @synthesize selectorWithoutArguments;
@property(nonatomic) SEL selectorWithNewValue; // @synthesize selectorWithNewValue;
@property(nonatomic) SEL selector; // @synthesize selector;
@property(retain, nonatomic) NSString *keyPath; // @synthesize keyPath;
@property(nonatomic) id target; // @synthesize target;
@property(nonatomic) id observer; // @synthesize observer;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)unsubscribe;
- (void)subscribe;
- (SEL)anySelector;
- (void)dealloc;

@end

