//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <AppKit/NSResponder.h>

#import "NSUserInterfaceValidations-Protocol.h"
#import "NSValidatedUserInterfaceItem-Protocol.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface OAMultipleSelection : NSResponder <NSValidatedUserInterfaceItem, NSUserInterfaceValidations>
{
    NSArray *objects;
    SEL action;
}

+ (id)selectionWithObjects:(id)arg1;
@property(nonatomic) SEL action; // @synthesize action;
@property(retain, nonatomic) NSArray *objects; // @synthesize objects;
- (id)targetForAction:(SEL)arg1 inObject:(id)arg2;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)canPerformAction:(SEL)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)tryToPerform:(SEL)arg1 with:(id)arg2;
- (long long)tag;
- (void)dealloc;

@end

