//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSURL;

__attribute__((visibility("hidden")))
@interface OAPropertyListController : NSObject
{
    BOOL isDirty;
    NSURL *plistURL;
    id plist;
}

@property(retain, nonatomic) id plist; // @synthesize plist;
@property(copy, nonatomic) NSURL *plistURL; // @synthesize plistURL;
- (BOOL)synchronize;
- (BOOL)synchronizeIfNeeded;
- (void)synchronizeLater;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (void)dealloc;

@end

