//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSFileHandle, NSString;

__attribute__((visibility("hidden")))
@interface OAPseudoTTY : NSObject
{
    NSString *name;
    NSFileHandle *masterFileHandle;
    NSFileHandle *slaveFileHandle;
}

@property(retain, nonatomic) NSFileHandle *slaveFileHandle; // @synthesize slaveFileHandle;
@property(retain, nonatomic) NSFileHandle *masterFileHandle; // @synthesize masterFileHandle;
@property(copy, nonatomic) NSString *name; // @synthesize name;
- (void)dealloc;
- (id)init;

@end

