//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSXMLParserDelegate-Protocol.h"

@class NSData, NSDictionary, NSError, NSMutableArray, NSMutableDictionary, NSMutableString, NSString, NSXMLParser;

__attribute__((visibility("hidden")))
@interface OAXMLDecoder : NSObject <NSXMLParserDelegate>
{
    NSData *xmlData;
    NSXMLParser *xmlParser;
    NSString *currentString;
    NSDictionary *currentAttributes;
    NSString *currentQualifiedName;
    NSString *currentNamespaceURI;
    NSString *currentElementName;
    NSError *error;
    NSMutableArray *startMapStack;
    NSMutableArray *endMapStack;
    NSMutableDictionary *currentStartMap;
    NSMutableDictionary *currentEndMap;
    NSMutableString *currentStringBuffer;
    BOOL caseInsensitive;
    BOOL succeed;
    BOOL traceParsing;
}

@property(nonatomic) BOOL traceParsing; // @synthesize traceParsing;
@property(nonatomic) BOOL succeed; // @synthesize succeed;
@property(nonatomic) BOOL caseInsensitive; // @synthesize caseInsensitive;
@property(retain, nonatomic) NSMutableString *currentStringBuffer; // @synthesize currentStringBuffer;
@property(retain, nonatomic) NSMutableDictionary *currentEndMap; // @synthesize currentEndMap;
@property(retain, nonatomic) NSMutableDictionary *currentStartMap; // @synthesize currentStartMap;
@property(retain, nonatomic) NSMutableArray *endMapStack; // @synthesize endMapStack;
@property(retain, nonatomic) NSMutableArray *startMapStack; // @synthesize startMapStack;
@property(copy, nonatomic) NSError *error; // @synthesize error;
@property(copy, nonatomic) NSString *currentElementName; // @synthesize currentElementName;
@property(copy, nonatomic) NSString *currentNamespaceURI; // @synthesize currentNamespaceURI;
@property(copy, nonatomic) NSString *currentQualifiedName; // @synthesize currentQualifiedName;
@property(retain, nonatomic) NSDictionary *currentAttributes; // @synthesize currentAttributes;
@property(retain, nonatomic) NSXMLParser *xmlParser; // @synthesize xmlParser;
@property(retain, nonatomic) NSData *xmlData; // @synthesize xmlData;
- (void)debugElementWithMessage:(id)arg1;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
@property(readonly, nonatomic) NSString *currentStringStripped;
@property(readonly, nonatomic) NSString *currentString; // @synthesize currentString;
- (id)attributeForName:(id)arg1;
- (void)endElements:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)endElement:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)startOptionalElements:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)startElements:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)startOptionalElement:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)startElement:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)parseElements:(id)arg1 startBlock:(CDUnknownBlockType)arg2 endBlock:(CDUnknownBlockType)arg3;
- (void)parseElement:(id)arg1 startBlock:(CDUnknownBlockType)arg2 endBlock:(CDUnknownBlockType)arg3;
- (void)decodeWithObject:(id)arg1 startSelector:(SEL)arg2 endBlock:(CDUnknownBlockType)arg3;
- (void)decodeWithObject:(id)arg1 startSelector:(SEL)arg2 endSelector:(SEL)arg3;
- (void)decodeWithObject:(id)arg1 startSelector:(SEL)arg2;
- (void)dealloc;

@end

